// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/market-simulation/market_simulation.proto

package market_simulation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketSimulationService_StartSimulation_FullMethodName     = "/market_simulation.MarketSimulationService/StartSimulation"
	MarketSimulationService_StopSimulation_FullMethodName      = "/market_simulation.MarketSimulationService/StopSimulation"
	MarketSimulationService_GetSimulationStatus_FullMethodName = "/market_simulation.MarketSimulationService/GetSimulationStatus"
)

// MarketSimulationServiceClient is the client API for MarketSimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketSimulationService 提供市场模拟服务
type MarketSimulationServiceClient interface {
	// 启动模拟
	StartSimulation(ctx context.Context, in *StartSimulationRequest, opts ...grpc.CallOption) (*StartSimulationResponse, error)
	// 停止模拟
	StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*StopSimulationResponse, error)
	// 获取模拟状态
	GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error)
}

type marketSimulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketSimulationServiceClient(cc grpc.ClientConnInterface) MarketSimulationServiceClient {
	return &marketSimulationServiceClient{cc}
}

func (c *marketSimulationServiceClient) StartSimulation(ctx context.Context, in *StartSimulationRequest, opts ...grpc.CallOption) (*StartSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSimulationResponse)
	err := c.cc.Invoke(ctx, MarketSimulationService_StartSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSimulationServiceClient) StopSimulation(ctx context.Context, in *StopSimulationRequest, opts ...grpc.CallOption) (*StopSimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSimulationResponse)
	err := c.cc.Invoke(ctx, MarketSimulationService_StopSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSimulationServiceClient) GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimulationStatusResponse)
	err := c.cc.Invoke(ctx, MarketSimulationService_GetSimulationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketSimulationServiceServer is the server API for MarketSimulationService service.
// All implementations must embed UnimplementedMarketSimulationServiceServer
// for forward compatibility.
//
// MarketSimulationService 提供市场模拟服务
type MarketSimulationServiceServer interface {
	// 启动模拟
	StartSimulation(context.Context, *StartSimulationRequest) (*StartSimulationResponse, error)
	// 停止模拟
	StopSimulation(context.Context, *StopSimulationRequest) (*StopSimulationResponse, error)
	// 获取模拟状态
	GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*GetSimulationStatusResponse, error)
	mustEmbedUnimplementedMarketSimulationServiceServer()
}

// UnimplementedMarketSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketSimulationServiceServer struct{}

func (UnimplementedMarketSimulationServiceServer) StartSimulation(context.Context, *StartSimulationRequest) (*StartSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSimulation not implemented")
}
func (UnimplementedMarketSimulationServiceServer) StopSimulation(context.Context, *StopSimulationRequest) (*StopSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSimulation not implemented")
}
func (UnimplementedMarketSimulationServiceServer) GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*GetSimulationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimulationStatus not implemented")
}
func (UnimplementedMarketSimulationServiceServer) mustEmbedUnimplementedMarketSimulationServiceServer() {
}
func (UnimplementedMarketSimulationServiceServer) testEmbeddedByValue() {}

// UnsafeMarketSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketSimulationServiceServer will
// result in compilation errors.
type UnsafeMarketSimulationServiceServer interface {
	mustEmbedUnimplementedMarketSimulationServiceServer()
}

func RegisterMarketSimulationServiceServer(s grpc.ServiceRegistrar, srv MarketSimulationServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketSimulationService_ServiceDesc, srv)
}

func _MarketSimulationService_StartSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSimulationServiceServer).StartSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSimulationService_StartSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSimulationServiceServer).StartSimulation(ctx, req.(*StartSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSimulationService_StopSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSimulationServiceServer).StopSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSimulationService_StopSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSimulationServiceServer).StopSimulation(ctx, req.(*StopSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSimulationService_GetSimulationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSimulationServiceServer).GetSimulationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSimulationService_GetSimulationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSimulationServiceServer).GetSimulationStatus(ctx, req.(*GetSimulationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketSimulationService_ServiceDesc is the grpc.ServiceDesc for MarketSimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketSimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market_simulation.MarketSimulationService",
	HandlerType: (*MarketSimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSimulation",
			Handler:    _MarketSimulationService_StartSimulation_Handler,
		},
		{
			MethodName: "StopSimulation",
			Handler:    _MarketSimulationService_StopSimulation_Handler,
		},
		{
			MethodName: "GetSimulationStatus",
			Handler:    _MarketSimulationService_GetSimulationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/market-simulation/market_simulation.proto",
}
