// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/risk/risk.proto

package risk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskService_AssessRisk_FullMethodName     = "/risk.RiskService/AssessRisk" // RiskService_AssessRisk_FullMethodName RiskSERVICEAssessRiskFullMethod名称
	RiskService_GetRiskMetrics_FullMethodName = "/risk.RiskService/GetRiskMetrics" // RiskService_GetRiskMetrics_FullMethodName RiskSERVICE获取RiskMetricsFullMethod名称
	RiskService_CheckRiskLimit_FullMethodName = "/risk.RiskService/CheckRiskLimit" // RiskService_CheckRiskLimit_FullMethodName RiskSERVICECheckRisk限制FullMethod名称
	RiskService_GetRiskAlerts_FullMethodName  = "/risk.RiskService/GetRiskAlerts" // RiskService_GetRiskAlerts_FullMethodName RiskSERVICE获取RiskAlertsFullMethod名称
)

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 风险管理服务
// RiskServiceClient 表示RiskSERVICE客户端结构体。
type RiskServiceClient interface {
	// 评估风险
	AssessRisk(ctx context.Context, in *AssessRiskRequest, opts ...grpc.CallOption) (*RiskAssessmentResponse, error)
	// 获取风险指标
	GetRiskMetrics(ctx context.Context, in *GetRiskMetricsRequest, opts ...grpc.CallOption) (*RiskMetricsResponse, error)
	// 检查风险限额
	CheckRiskLimit(ctx context.Context, in *CheckRiskLimitRequest, opts ...grpc.CallOption) (*RiskLimitResponse, error)
	// 获取风险警告
	GetRiskAlerts(ctx context.Context, in *GetRiskAlertsRequest, opts ...grpc.CallOption) (*RiskAlertsResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewRiskServiceClient 创建新的创建一个新的实例RiskSERVICE客户端.
func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

// AssessRisk 执行AssessRisk逻辑。
func (c *riskServiceClient) AssessRisk(ctx context.Context, in *AssessRiskRequest, opts ...grpc.CallOption) (*RiskAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskAssessmentResponse)
	err := c.cc.Invoke(ctx, RiskService_AssessRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRiskMetrics 获取RiskMetrics.
func (c *riskServiceClient) GetRiskMetrics(ctx context.Context, in *GetRiskMetricsRequest, opts ...grpc.CallOption) (*RiskMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskMetricsResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRiskMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckRiskLimit 执行CheckRisk限制逻辑。
func (c *riskServiceClient) CheckRiskLimit(ctx context.Context, in *CheckRiskLimitRequest, opts ...grpc.CallOption) (*RiskLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskLimitResponse)
	err := c.cc.Invoke(ctx, RiskService_CheckRiskLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRiskAlerts 获取RiskAlerts.
func (c *riskServiceClient) GetRiskAlerts(ctx context.Context, in *GetRiskAlertsRequest, opts ...grpc.CallOption) (*RiskAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskAlertsResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRiskAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility.
//
// 风险管理服务
// RiskServiceServer 表示RiskSERVICE服务端结构体。
type RiskServiceServer interface {
	// 评估风险
	AssessRisk(context.Context, *AssessRiskRequest) (*RiskAssessmentResponse, error)
	// 获取风险指标
	GetRiskMetrics(context.Context, *GetRiskMetricsRequest) (*RiskMetricsResponse, error)
	// 检查风险限额
	CheckRiskLimit(context.Context, *CheckRiskLimitRequest) (*RiskLimitResponse, error)
	// 获取风险警告
	GetRiskAlerts(context.Context, *GetRiskAlertsRequest) (*RiskAlertsResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedRiskServiceServer 表示未实现的RiskSERVICE服务端结构体。
type UnimplementedRiskServiceServer struct{}

// AssessRisk 执行AssessRisk逻辑。
func (UnimplementedRiskServiceServer) AssessRisk(context.Context, *AssessRiskRequest) (*RiskAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessRisk not implemented")
}
// GetRiskMetrics 获取RiskMetrics.
func (UnimplementedRiskServiceServer) GetRiskMetrics(context.Context, *GetRiskMetricsRequest) (*RiskMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskMetrics not implemented")
}
// CheckRiskLimit 执行CheckRisk限制逻辑。
func (UnimplementedRiskServiceServer) CheckRiskLimit(context.Context, *CheckRiskLimitRequest) (*RiskLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRiskLimit not implemented")
}
// GetRiskAlerts 获取RiskAlerts.
func (UnimplementedRiskServiceServer) GetRiskAlerts(context.Context, *GetRiskAlertsRequest) (*RiskAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskAlerts not implemented")
}
func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}
func (UnimplementedRiskServiceServer) testEmbeddedByValue()                     {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
// UnsafeRiskServiceServer 表示UnsafeRiskSERVICE服务端结构体。
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

// RegisterRiskServiceServer 执行RegisterRiskSERVICE服务端逻辑。
func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	// If the following call pancis, it indicates UnimplementedRiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_AssessRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).AssessRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_AssessRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).AssessRisk(ctx, req.(*AssessRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRiskMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRiskMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRiskMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRiskMetrics(ctx, req.(*GetRiskMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_CheckRiskLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRiskLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CheckRiskLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CheckRiskLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CheckRiskLimit(ctx, req.(*CheckRiskLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRiskAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRiskAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRiskAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRiskAlerts(ctx, req.(*GetRiskAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessRisk",
			Handler:    _RiskService_AssessRisk_Handler,
		},
		{
			MethodName: "GetRiskMetrics",
			Handler:    _RiskService_GetRiskMetrics_Handler,
		},
		{
			MethodName: "CheckRiskLimit",
			Handler:    _RiskService_CheckRiskLimit_Handler,
		},
		{
			MethodName: "GetRiskAlerts",
			Handler:    _RiskService_GetRiskAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/risk/risk.proto",
}
