// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: clearing/clearing.proto

package clearing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 交易清算请求。
type SettleTradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原始成交 ID。
	TradeId string `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// 买方用户 ID。
	BuyUserId string `protobuf:"bytes,2,opt,name=buy_user_id,json=buyUserId,proto3" json:"buy_user_id,omitempty"`
	// 卖方用户 ID。
	SellUserId string `protobuf:"bytes,3,opt,name=sell_user_id,json=sellUserId,proto3" json:"sell_user_id,omitempty"`
	// 交易对。
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 数量。
	Quantity string `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// 成交价。
	Price         string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleTradeRequest) Reset() {
	*x = SettleTradeRequest{}
	mi := &file_clearing_clearing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTradeRequest) ProtoMessage() {}

func (x *SettleTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTradeRequest.ProtoReflect.Descriptor instead.
func (*SettleTradeRequest) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{0}
}

func (x *SettleTradeRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *SettleTradeRequest) GetBuyUserId() string {
	if x != nil {
		return x.BuyUserId
	}
	return ""
}

func (x *SettleTradeRequest) GetSellUserId() string {
	if x != nil {
		return x.SellUserId
	}
	return ""
}

func (x *SettleTradeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SettleTradeRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *SettleTradeRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

// 单笔清算结果。
type SettlementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 结算流水 ID。
	SettlementId string `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// 成交 ID。
	TradeId string `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// 状态 (COMPLETED, FAILED)。
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 确认时间戳。
	SettlementTime int64 `protobuf:"varint,4,opt,name=settlement_time,json=settlementTime,proto3" json:"settlement_time,omitempty"`
	// 异常错误描述。
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_clearing_clearing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{1}
}

func (x *SettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *SettlementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettlementResponse) GetSettlementTime() int64 {
	if x != nil {
		return x.SettlementTime
	}
	return 0
}

func (x *SettlementResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 历史查询请求。
type GetSettlementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID。
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 返回限制。
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsRequest) Reset() {
	*x = GetSettlementsRequest{}
	mi := &file_clearing_clearing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsRequest) ProtoMessage() {}

func (x *GetSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettlementsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSettlementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 清算单详情。
type Settlement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 流水 ID。
	SettlementId string `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	// 成交 ID。
	TradeId string `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// 当前状态。
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 时间。
	SettlementTime int64 `protobuf:"varint,4,opt,name=settlement_time,json=settlementTime,proto3" json:"settlement_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Settlement) Reset() {
	*x = Settlement{}
	mi := &file_clearing_clearing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settlement) ProtoMessage() {}

func (x *Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settlement.ProtoReflect.Descriptor instead.
func (*Settlement) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{3}
}

func (x *Settlement) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *Settlement) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Settlement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Settlement) GetSettlementTime() int64 {
	if x != nil {
		return x.SettlementTime
	}
	return 0
}

// 列表响应。
type ListSettlementsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 清算单列表序列。
	Settlements   []*Settlement `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsResponse) Reset() {
	*x = ListSettlementsResponse{}
	mi := &file_clearing_clearing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsResponse) ProtoMessage() {}

func (x *ListSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{4}
}

func (x *ListSettlementsResponse) GetSettlements() []*Settlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

// 日终清算请求。
type ExecuteEODClearingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标业务日期 (YYYY-MM-DD)。
	ClearingDate  string `protobuf:"bytes,1,opt,name=clearing_date,json=clearingDate,proto3" json:"clearing_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEODClearingRequest) Reset() {
	*x = ExecuteEODClearingRequest{}
	mi := &file_clearing_clearing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEODClearingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEODClearingRequest) ProtoMessage() {}

func (x *ExecuteEODClearingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEODClearingRequest.ProtoReflect.Descriptor instead.
func (*ExecuteEODClearingRequest) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteEODClearingRequest) GetClearingDate() string {
	if x != nil {
		return x.ClearingDate
	}
	return ""
}

// 批处理响应概要。
type EODClearingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID。
	ClearingId string `protobuf:"bytes,1,opt,name=clearing_id,json=clearingId,proto3" json:"clearing_id,omitempty"`
	// 任务状态。
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 启动时间。
	StartTime int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 完成时间。
	EndTime int64 `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// 成功结算笔数。
	TradesSettled int64 `protobuf:"varint,5,opt,name=trades_settled,json=tradesSettled,proto3" json:"trades_settled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EODClearingResponse) Reset() {
	*x = EODClearingResponse{}
	mi := &file_clearing_clearing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EODClearingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EODClearingResponse) ProtoMessage() {}

func (x *EODClearingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EODClearingResponse.ProtoReflect.Descriptor instead.
func (*EODClearingResponse) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{6}
}

func (x *EODClearingResponse) GetClearingId() string {
	if x != nil {
		return x.ClearingId
	}
	return ""
}

func (x *EODClearingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EODClearingResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EODClearingResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *EODClearingResponse) GetTradesSettled() int64 {
	if x != nil {
		return x.TradesSettled
	}
	return 0
}

// 任务进度查询请求。
type GetClearingStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID。
	ClearingId    string `protobuf:"bytes,1,opt,name=clearing_id,json=clearingId,proto3" json:"clearing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClearingStatusRequest) Reset() {
	*x = GetClearingStatusRequest{}
	mi := &file_clearing_clearing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClearingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClearingStatusRequest) ProtoMessage() {}

func (x *GetClearingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClearingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClearingStatusRequest) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{7}
}

func (x *GetClearingStatusRequest) GetClearingId() string {
	if x != nil {
		return x.ClearingId
	}
	return ""
}

// 进度详情响应。
type ClearingStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务 ID。
	ClearingId string `protobuf:"bytes,1,opt,name=clearing_id,json=clearingId,proto3" json:"clearing_id,omitempty"`
	// 状态。
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 完成百分比。
	ProgressPercentage int64 `protobuf:"varint,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	// 已处理记录数。
	TradesProcessed int64 `protobuf:"varint,4,opt,name=trades_processed,json=tradesProcessed,proto3" json:"trades_processed,omitempty"`
	// 总待处理记录数。
	TradesTotal   int64 `protobuf:"varint,5,opt,name=trades_total,json=tradesTotal,proto3" json:"trades_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearingStatusResponse) Reset() {
	*x = ClearingStatusResponse{}
	mi := &file_clearing_clearing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearingStatusResponse) ProtoMessage() {}

func (x *ClearingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clearing_clearing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearingStatusResponse.ProtoReflect.Descriptor instead.
func (*ClearingStatusResponse) Descriptor() ([]byte, []int) {
	return file_clearing_clearing_proto_rawDescGZIP(), []int{8}
}

func (x *ClearingStatusResponse) GetClearingId() string {
	if x != nil {
		return x.ClearingId
	}
	return ""
}

func (x *ClearingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClearingStatusResponse) GetProgressPercentage() int64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *ClearingStatusResponse) GetTradesProcessed() int64 {
	if x != nil {
		return x.TradesProcessed
	}
	return 0
}

func (x *ClearingStatusResponse) GetTradesTotal() int64 {
	if x != nil {
		return x.TradesTotal
	}
	return 0
}

var File_clearing_clearing_proto protoreflect.FileDescriptor

const file_clearing_clearing_proto_rawDesc = "" +
	"\n" +
	"\x17clearing/clearing.proto\x12\bclearing\"\xbb\x01\n" +
	"\x12SettleTradeRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x1e\n" +
	"\vbuy_user_id\x18\x02 \x01(\tR\tbuyUserId\x12 \n" +
	"\fsell_user_id\x18\x03 \x01(\tR\n" +
	"sellUserId\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\"\xba\x01\n" +
	"\x12SettlementResponse\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fsettlement_time\x18\x04 \x01(\x03R\x0esettlementTime\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"F\n" +
	"\x15GetSettlementsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x8d\x01\n" +
	"\n" +
	"Settlement\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fsettlement_time\x18\x04 \x01(\x03R\x0esettlementTime\"Q\n" +
	"\x17ListSettlementsResponse\x126\n" +
	"\vsettlements\x18\x01 \x03(\v2\x14.clearing.SettlementR\vsettlements\"@\n" +
	"\x19ExecuteEODClearingRequest\x12#\n" +
	"\rclearing_date\x18\x01 \x01(\tR\fclearingDate\"\xaf\x01\n" +
	"\x13EODClearingResponse\x12\x1f\n" +
	"\vclearing_id\x18\x01 \x01(\tR\n" +
	"clearingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12%\n" +
	"\x0etrades_settled\x18\x05 \x01(\x03R\rtradesSettled\";\n" +
	"\x18GetClearingStatusRequest\x12\x1f\n" +
	"\vclearing_id\x18\x01 \x01(\tR\n" +
	"clearingId\"\xd0\x01\n" +
	"\x16ClearingStatusResponse\x12\x1f\n" +
	"\vclearing_id\x18\x01 \x01(\tR\n" +
	"clearingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x03R\x12progressPercentage\x12)\n" +
	"\x10trades_processed\x18\x04 \x01(\x03R\x0ftradesProcessed\x12!\n" +
	"\ftrades_total\x18\x05 \x01(\x03R\vtradesTotal2\xe7\x02\n" +
	"\x0fClearingService\x12I\n" +
	"\vSettleTrade\x12\x1c.clearing.SettleTradeRequest\x1a\x1c.clearing.SettlementResponse\x12T\n" +
	"\x0eGetSettlements\x12\x1f.clearing.GetSettlementsRequest\x1a!.clearing.ListSettlementsResponse\x12X\n" +
	"\x12ExecuteEODClearing\x12#.clearing.ExecuteEODClearingRequest\x1a\x1d.clearing.EODClearingResponse\x12Y\n" +
	"\x11GetClearingStatus\x12\".clearing.GetClearingStatusRequest\x1a .clearing.ClearingStatusResponseB=Z;github.com/fynnwu/FinancialTrading/go-api/clearing;clearingb\x06proto3"

var (
	file_clearing_clearing_proto_rawDescOnce sync.Once
	file_clearing_clearing_proto_rawDescData []byte
)

func file_clearing_clearing_proto_rawDescGZIP() []byte {
	file_clearing_clearing_proto_rawDescOnce.Do(func() {
		file_clearing_clearing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clearing_clearing_proto_rawDesc), len(file_clearing_clearing_proto_rawDesc)))
	})
	return file_clearing_clearing_proto_rawDescData
}

var file_clearing_clearing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_clearing_clearing_proto_goTypes = []any{
	(*SettleTradeRequest)(nil),        // 0: clearing.SettleTradeRequest
	(*SettlementResponse)(nil),        // 1: clearing.SettlementResponse
	(*GetSettlementsRequest)(nil),     // 2: clearing.GetSettlementsRequest
	(*Settlement)(nil),                // 3: clearing.Settlement
	(*ListSettlementsResponse)(nil),   // 4: clearing.ListSettlementsResponse
	(*ExecuteEODClearingRequest)(nil), // 5: clearing.ExecuteEODClearingRequest
	(*EODClearingResponse)(nil),       // 6: clearing.EODClearingResponse
	(*GetClearingStatusRequest)(nil),  // 7: clearing.GetClearingStatusRequest
	(*ClearingStatusResponse)(nil),    // 8: clearing.ClearingStatusResponse
}
var file_clearing_clearing_proto_depIdxs = []int32{
	3, // 0: clearing.ListSettlementsResponse.settlements:type_name -> clearing.Settlement
	0, // 1: clearing.ClearingService.SettleTrade:input_type -> clearing.SettleTradeRequest
	2, // 2: clearing.ClearingService.GetSettlements:input_type -> clearing.GetSettlementsRequest
	5, // 3: clearing.ClearingService.ExecuteEODClearing:input_type -> clearing.ExecuteEODClearingRequest
	7, // 4: clearing.ClearingService.GetClearingStatus:input_type -> clearing.GetClearingStatusRequest
	1, // 5: clearing.ClearingService.SettleTrade:output_type -> clearing.SettlementResponse
	4, // 6: clearing.ClearingService.GetSettlements:output_type -> clearing.ListSettlementsResponse
	6, // 7: clearing.ClearingService.ExecuteEODClearing:output_type -> clearing.EODClearingResponse
	8, // 8: clearing.ClearingService.GetClearingStatus:output_type -> clearing.ClearingStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clearing_clearing_proto_init() }
func file_clearing_clearing_proto_init() {
	if File_clearing_clearing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clearing_clearing_proto_rawDesc), len(file_clearing_clearing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clearing_clearing_proto_goTypes,
		DependencyIndexes: file_clearing_clearing_proto_depIdxs,
		MessageInfos:      file_clearing_clearing_proto_msgTypes,
	}.Build()
	File_clearing_clearing_proto = out.File
	file_clearing_clearing_proto_goTypes = nil
	file_clearing_clearing_proto_depIdxs = nil
}
