// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/quant/quant.proto

package quant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Strategy 表示Strategy结构体。
type Strategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 描述
	Script        string                 `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"` // 策略脚本或配置
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // 状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created在
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Updated在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_api_quant_quant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*Strategy) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{0}
}

// GetId 获取唯一标识.
func (x *Strategy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetName 获取名称.
func (x *Strategy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetDescription 获取描述.
func (x *Strategy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetScript 获取Script.
func (x *Strategy) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// GetStatus 获取STATUS.
func (x *Strategy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCreatedAt 获取Created在.
func (x *Strategy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetUpdatedAt 获取Updated在.
func (x *Strategy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BacktestResult 表示Backtest结果结构体。
type BacktestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一标识
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // Strategy唯一标识
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 结束时间
	TotalReturn   float64                `protobuf:"fixed64,6,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"` // 总数返回
	MaxDrawdown   float64                `protobuf:"fixed64,7,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"` // 最大Drawdown
	SharpeRatio   float64                `protobuf:"fixed64,8,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"` // SharpeRatio
	TotalTrades   int32                  `protobuf:"varint,9,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"` // 总数Trades
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // 状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *BacktestResult) Reset() {
	*x = BacktestResult{}
	mi := &file_api_quant_quant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *BacktestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*BacktestResult) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *BacktestResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestResult.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*BacktestResult) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{1}
}

// GetId 获取唯一标识.
func (x *BacktestResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetStrategyId 获取Strategy唯一标识.
func (x *BacktestResult) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// GetSymbol 获取交易对.
func (x *BacktestResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetStartTime 获取开始时间.
func (x *BacktestResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// GetEndTime 获取结束时间.
func (x *BacktestResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetTotalReturn 获取总数返回.
func (x *BacktestResult) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

// GetMaxDrawdown 获取最大Drawdown.
func (x *BacktestResult) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

// GetSharpeRatio 获取SharpeRatio.
func (x *BacktestResult) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

// GetTotalTrades 获取总数Trades.
func (x *BacktestResult) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

// GetStatus 获取STATUS.
func (x *BacktestResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCreatedAt 获取Created在.
func (x *BacktestResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateStrategyRequest 表示创建Strategy请求结构体。
type CreateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 描述
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"` // Script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *CreateStrategyRequest) Reset() {
	*x = CreateStrategyRequest{}
	mi := &file_api_quant_quant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *CreateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*CreateStrategyRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *CreateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*CreateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{2}
}

// GetName 获取名称.
func (x *CreateStrategyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetDescription 获取描述.
func (x *CreateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetScript 获取Script.
func (x *CreateStrategyRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// CreateStrategyResponse 表示创建Strategy响应结构体。
type CreateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // Strategy唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *CreateStrategyResponse) Reset() {
	*x = CreateStrategyResponse{}
	mi := &file_api_quant_quant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *CreateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*CreateStrategyResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *CreateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*CreateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{3}
}

// GetStrategyId 获取Strategy唯一标识.
func (x *CreateStrategyResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// GetStrategyRequest 表示获取Strategy请求结构体。
type GetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetStrategyRequest) Reset() {
	*x = GetStrategyRequest{}
	mi := &file_api_quant_quant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetStrategyRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{4}
}

// GetId 获取唯一标识.
func (x *GetStrategyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetStrategyResponse 表示获取Strategy响应结构体。
type GetStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      *Strategy              `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // 策略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetStrategyResponse) Reset() {
	*x = GetStrategyResponse{}
	mi := &file_api_quant_quant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetStrategyResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{5}
}

// GetStrategy 获取Strategy.
func (x *GetStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

// RunBacktestRequest 表示RUNBacktest请求结构体。
type RunBacktestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StrategyId     string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // Strategy唯一标识
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 结束时间
	InitialCapital float64                `protobuf:"fixed64,5,opt,name=initial_capital,json=initialCapital,proto3" json:"initial_capital,omitempty"` // InitialCapital
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *RunBacktestRequest) Reset() {
	*x = RunBacktestRequest{}
	mi := &file_api_quant_quant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *RunBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*RunBacktestRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *RunBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*RunBacktestRequest) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{6}
}

// GetStrategyId 获取Strategy唯一标识.
func (x *RunBacktestRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// GetSymbol 获取交易对.
func (x *RunBacktestRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetStartTime 获取开始时间.
func (x *RunBacktestRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// GetEndTime 获取结束时间.
func (x *RunBacktestRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetInitialCapital 获取InitialCapital.
func (x *RunBacktestRequest) GetInitialCapital() float64 {
	if x != nil {
		return x.InitialCapital
	}
	return 0
}

// RunBacktestResponse 表示RUNBacktest响应结构体。
type RunBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BacktestId    string                 `protobuf:"bytes,1,opt,name=backtest_id,json=backtestId,proto3" json:"backtest_id,omitempty"` // Backtest唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *RunBacktestResponse) Reset() {
	*x = RunBacktestResponse{}
	mi := &file_api_quant_quant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *RunBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*RunBacktestResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *RunBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*RunBacktestResponse) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{7}
}

// GetBacktestId 获取Backtest唯一标识.
func (x *RunBacktestResponse) GetBacktestId() string {
	if x != nil {
		return x.BacktestId
	}
	return ""
}

// GetBacktestResultRequest 表示获取Backtest结果请求结构体。
type GetBacktestResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetBacktestResultRequest) Reset() {
	*x = GetBacktestResultRequest{}
	mi := &file_api_quant_quant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetBacktestResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetBacktestResultRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetBacktestResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacktestResultRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetBacktestResultRequest) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{8}
}

// GetId 获取唯一标识.
func (x *GetBacktestResultRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetBacktestResultResponse 表示获取Backtest结果响应结构体。
type GetBacktestResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BacktestResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetBacktestResultResponse) Reset() {
	*x = GetBacktestResultResponse{}
	mi := &file_api_quant_quant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetBacktestResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetBacktestResultResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetBacktestResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quant_quant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacktestResultResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetBacktestResultResponse) Descriptor() ([]byte, []int) {
	return file_api_quant_quant_proto_rawDescGZIP(), []int{9}
}

// GetResult 获取结果.
func (x *GetBacktestResultResponse) GetResult() *BacktestResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_quant_quant_proto protoreflect.FileDescriptor

const file_api_quant_quant_proto_rawDesc = "" +
	"\n" +
	"\x15api/quant/quant.proto\x12\x05quant\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\bStrategy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x04 \x01(\tR\x06script\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaa\x03\n" +
	"\x0eBacktestResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12!\n" +
	"\ftotal_return\x18\x06 \x01(\x01R\vtotalReturn\x12!\n" +
	"\fmax_drawdown\x18\a \x01(\x01R\vmaxDrawdown\x12!\n" +
	"\fsharpe_ratio\x18\b \x01(\x01R\vsharpeRatio\x12!\n" +
	"\ftotal_trades\x18\t \x01(\x05R\vtotalTrades\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x15CreateStrategyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\"9\n" +
	"\x16CreateStrategyResponse\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\"$\n" +
	"\x12GetStrategyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x13GetStrategyResponse\x12+\n" +
	"\bstrategy\x18\x01 \x01(\v2\x0f.quant.StrategyR\bstrategy\"\xe8\x01\n" +
	"\x12RunBacktestRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12'\n" +
	"\x0finitial_capital\x18\x05 \x01(\x01R\x0einitialCapital\"6\n" +
	"\x13RunBacktestResponse\x12\x1f\n" +
	"\vbacktest_id\x18\x01 \x01(\tR\n" +
	"backtestId\"*\n" +
	"\x18GetBacktestResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x19GetBacktestResultResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.quant.BacktestResultR\x06result2\xc1\x02\n" +
	"\fQuantService\x12M\n" +
	"\x0eCreateStrategy\x12\x1c.quant.CreateStrategyRequest\x1a\x1d.quant.CreateStrategyResponse\x12D\n" +
	"\vGetStrategy\x12\x19.quant.GetStrategyRequest\x1a\x1a.quant.GetStrategyResponse\x12D\n" +
	"\vRunBacktest\x12\x19.quant.RunBacktestRequest\x1a\x1a.quant.RunBacktestResponse\x12V\n" +
	"\x11GetBacktestResult\x12\x1f.quant.GetBacktestResultRequest\x1a .quant.GetBacktestResultResponseB7Z5github.com/wyfcoding/financialTrading/go-api/quant;quantb\x06proto3"

var (
	file_api_quant_quant_proto_rawDescOnce sync.Once
	file_api_quant_quant_proto_rawDescData []byte
)

func file_api_quant_quant_proto_rawDescGZIP() []byte {
	file_api_quant_quant_proto_rawDescOnce.Do(func() {
		file_api_quant_quant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_quant_quant_proto_rawDesc), len(file_api_quant_quant_proto_rawDesc)))
	})
	return file_api_quant_quant_proto_rawDescData
}

var file_api_quant_quant_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_quant_quant_proto_goTypes = []any{
	(*Strategy)(nil),                  // 0: quant.Strategy
	(*BacktestResult)(nil),            // 1: quant.BacktestResult
	(*CreateStrategyRequest)(nil),     // 2: quant.CreateStrategyRequest
	(*CreateStrategyResponse)(nil),    // 3: quant.CreateStrategyResponse
	(*GetStrategyRequest)(nil),        // 4: quant.GetStrategyRequest
	(*GetStrategyResponse)(nil),       // 5: quant.GetStrategyResponse
	(*RunBacktestRequest)(nil),        // 6: quant.RunBacktestRequest
	(*RunBacktestResponse)(nil),       // 7: quant.RunBacktestResponse
	(*GetBacktestResultRequest)(nil),  // 8: quant.GetBacktestResultRequest
	(*GetBacktestResultResponse)(nil), // 9: quant.GetBacktestResultResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_api_quant_quant_proto_depIdxs = []int32{
	10, // 0: quant.Strategy.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: quant.Strategy.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: quant.BacktestResult.start_time:type_name -> google.protobuf.Timestamp
	10, // 3: quant.BacktestResult.end_time:type_name -> google.protobuf.Timestamp
	10, // 4: quant.BacktestResult.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: quant.GetStrategyResponse.strategy:type_name -> quant.Strategy
	10, // 6: quant.RunBacktestRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 7: quant.RunBacktestRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 8: quant.GetBacktestResultResponse.result:type_name -> quant.BacktestResult
	2,  // 9: quant.QuantService.CreateStrategy:input_type -> quant.CreateStrategyRequest
	4,  // 10: quant.QuantService.GetStrategy:input_type -> quant.GetStrategyRequest
	6,  // 11: quant.QuantService.RunBacktest:input_type -> quant.RunBacktestRequest
	8,  // 12: quant.QuantService.GetBacktestResult:input_type -> quant.GetBacktestResultRequest
	3,  // 13: quant.QuantService.CreateStrategy:output_type -> quant.CreateStrategyResponse
	5,  // 14: quant.QuantService.GetStrategy:output_type -> quant.GetStrategyResponse
	7,  // 15: quant.QuantService.RunBacktest:output_type -> quant.RunBacktestResponse
	9,  // 16: quant.QuantService.GetBacktestResult:output_type -> quant.GetBacktestResultResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_quant_quant_proto_init() }
func file_api_quant_quant_proto_init() {
	if File_api_quant_quant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_quant_quant_proto_rawDesc), len(file_api_quant_quant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_quant_quant_proto_goTypes,
		DependencyIndexes: file_api_quant_quant_proto_depIdxs,
		MessageInfos:      file_api_quant_quant_proto_msgTypes,
	}.Build()
	File_api_quant_quant_proto = out.File // File_api_quant_quant_proto 文件APIquantquantProto
	file_api_quant_quant_proto_goTypes = nil
	file_api_quant_quant_proto_depIdxs = nil
}
