// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/fix-gateway/fix_gateway.proto

package fix_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FIXGatewayService_SendOrder_FullMethodName        = "/fix_gateway.FIXGatewayService/SendOrder"
	FIXGatewayService_CancelOrder_FullMethodName      = "/fix_gateway.FIXGatewayService/CancelOrder"
	FIXGatewayService_GetSessionStatus_FullMethodName = "/fix_gateway.FIXGatewayService/GetSessionStatus"
)

// FIXGatewayServiceClient is the client API for FIXGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FIXGatawayService FIX 网关服务
// 提供管理 FIX 会话和发送消息的能力
type FIXGatewayServiceClient interface {
	// SendOrder 发送新订单消息 (NewOrderSingle - 35=D)
	SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error)
	// CancelOrder 发送取消订单消息 (OrderCancelRequest - 35=F)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// GetSessionStatus 获取会话状态
	GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error)
}

type fIXGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFIXGatewayServiceClient(cc grpc.ClientConnInterface) FIXGatewayServiceClient {
	return &fIXGatewayServiceClient{cc}
}

func (c *fIXGatewayServiceClient) SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendOrderResponse)
	err := c.cc.Invoke(ctx, FIXGatewayService_SendOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fIXGatewayServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, FIXGatewayService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fIXGatewayServiceClient) GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStatusResponse)
	err := c.cc.Invoke(ctx, FIXGatewayService_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FIXGatewayServiceServer is the server API for FIXGatewayService service.
// All implementations must embed UnimplementedFIXGatewayServiceServer
// for forward compatibility.
//
// FIXGatawayService FIX 网关服务
// 提供管理 FIX 会话和发送消息的能力
type FIXGatewayServiceServer interface {
	// SendOrder 发送新订单消息 (NewOrderSingle - 35=D)
	SendOrder(context.Context, *SendOrderRequest) (*SendOrderResponse, error)
	// CancelOrder 发送取消订单消息 (OrderCancelRequest - 35=F)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// GetSessionStatus 获取会话状态
	GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error)
	mustEmbedUnimplementedFIXGatewayServiceServer()
}

// UnimplementedFIXGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFIXGatewayServiceServer struct{}

func (UnimplementedFIXGatewayServiceServer) SendOrder(context.Context, *SendOrderRequest) (*SendOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrder not implemented")
}
func (UnimplementedFIXGatewayServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedFIXGatewayServiceServer) GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedFIXGatewayServiceServer) mustEmbedUnimplementedFIXGatewayServiceServer() {}
func (UnimplementedFIXGatewayServiceServer) testEmbeddedByValue()                           {}

// UnsafeFIXGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FIXGatewayServiceServer will
// result in compilation errors.
type UnsafeFIXGatewayServiceServer interface {
	mustEmbedUnimplementedFIXGatewayServiceServer()
}

func RegisterFIXGatewayServiceServer(s grpc.ServiceRegistrar, srv FIXGatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedFIXGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FIXGatewayService_ServiceDesc, srv)
}

func _FIXGatewayService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FIXGatewayServiceServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FIXGatewayService_SendOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FIXGatewayServiceServer).SendOrder(ctx, req.(*SendOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FIXGatewayService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FIXGatewayServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FIXGatewayService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FIXGatewayServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FIXGatewayService_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FIXGatewayServiceServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FIXGatewayService_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FIXGatewayServiceServer).GetSessionStatus(ctx, req.(*GetSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FIXGatewayService_ServiceDesc is the grpc.ServiceDesc for FIXGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FIXGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fix_gateway.FIXGatewayService",
	HandlerType: (*FIXGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOrder",
			Handler:    _FIXGatewayService_SendOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _FIXGatewayService_CancelOrder_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _FIXGatewayService_GetSessionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/fix-gateway/fix_gateway.proto",
}
