// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/market-making/market_making.proto

package market_making

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuoteStrategy 表示QuoteStrategy结构体。
type QuoteStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 唯一标识
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Spread        float64                `protobuf:"fixed64,3,opt,name=spread,proto3" json:"spread,omitempty"` // 目标点差
	MinOrderSize  float64                `protobuf:"fixed64,4,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"` // 最小订单大小
	MaxOrderSize  float64                `protobuf:"fixed64,5,opt,name=max_order_size,json=maxOrderSize,proto3" json:"max_order_size,omitempty"` // 最大订单大小
	MaxPosition   float64                `protobuf:"fixed64,6,opt,name=max_position,json=maxPosition,proto3" json:"max_position,omitempty"` // 最大Position
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // 状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created在
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Updated在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *QuoteStrategy) Reset() {
	*x = QuoteStrategy{}
	mi := &file_api_market_making_market_making_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *QuoteStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*QuoteStrategy) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *QuoteStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteStrategy.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*QuoteStrategy) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{0}
}

// GetId 获取唯一标识.
func (x *QuoteStrategy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSymbol 获取交易对.
func (x *QuoteStrategy) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetSpread 获取Spread.
func (x *QuoteStrategy) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

// GetMinOrderSize 获取最小订单大小.
func (x *QuoteStrategy) GetMinOrderSize() float64 {
	if x != nil {
		return x.MinOrderSize
	}
	return 0
}

// GetMaxOrderSize 获取最大订单大小.
func (x *QuoteStrategy) GetMaxOrderSize() float64 {
	if x != nil {
		return x.MaxOrderSize
	}
	return 0
}

// GetMaxPosition 获取最大Position.
func (x *QuoteStrategy) GetMaxPosition() float64 {
	if x != nil {
		return x.MaxPosition
	}
	return 0
}

// GetStatus 获取STATUS.
func (x *QuoteStrategy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCreatedAt 获取Created在.
func (x *QuoteStrategy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetUpdatedAt 获取Updated在.
func (x *QuoteStrategy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MarketMakingPerformance 表示市场MakingPerformance结构体。
type MarketMakingPerformance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	TotalPnl      float64                `protobuf:"fixed64,2,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"` // 总数Pnl
	TotalVolume   float64                `protobuf:"fixed64,3,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"` // 总数VOLUME
	TotalTrades   int32                  `protobuf:"varint,4,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"` // 总数Trades
	SharpeRatio   float64                `protobuf:"fixed64,5,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"` // SharpeRatio
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *MarketMakingPerformance) Reset() {
	*x = MarketMakingPerformance{}
	mi := &file_api_market_making_market_making_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *MarketMakingPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*MarketMakingPerformance) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *MarketMakingPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMakingPerformance.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*MarketMakingPerformance) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{1}
}

// GetSymbol 获取交易对.
func (x *MarketMakingPerformance) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetTotalPnl 获取总数Pnl.
func (x *MarketMakingPerformance) GetTotalPnl() float64 {
	if x != nil {
		return x.TotalPnl
	}
	return 0
}

// GetTotalVolume 获取总数VOLUME.
func (x *MarketMakingPerformance) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

// GetTotalTrades 获取总数Trades.
func (x *MarketMakingPerformance) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

// GetSharpeRatio 获取SharpeRatio.
func (x *MarketMakingPerformance) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

// GetStartTime 获取开始时间.
func (x *MarketMakingPerformance) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// GetEndTime 获取结束时间.
func (x *MarketMakingPerformance) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// SetStrategyRequest 表示SetStrategy请求结构体。
type SetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Spread        float64                `protobuf:"fixed64,2,opt,name=spread,proto3" json:"spread,omitempty"` // Spread
	MinOrderSize  float64                `protobuf:"fixed64,3,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"` // 最小订单大小
	MaxOrderSize  float64                `protobuf:"fixed64,4,opt,name=max_order_size,json=maxOrderSize,proto3" json:"max_order_size,omitempty"` // 最大订单大小
	MaxPosition   float64                `protobuf:"fixed64,5,opt,name=max_position,json=maxPosition,proto3" json:"max_position,omitempty"` // 最大Position
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *SetStrategyRequest) Reset() {
	*x = SetStrategyRequest{}
	mi := &file_api_market_making_market_making_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *SetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*SetStrategyRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *SetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStrategyRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*SetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{2}
}

// GetSymbol 获取交易对.
func (x *SetStrategyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetSpread 获取Spread.
func (x *SetStrategyRequest) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

// GetMinOrderSize 获取最小订单大小.
func (x *SetStrategyRequest) GetMinOrderSize() float64 {
	if x != nil {
		return x.MinOrderSize
	}
	return 0
}

// GetMaxOrderSize 获取最大订单大小.
func (x *SetStrategyRequest) GetMaxOrderSize() float64 {
	if x != nil {
		return x.MaxOrderSize
	}
	return 0
}

// GetMaxPosition 获取最大Position.
func (x *SetStrategyRequest) GetMaxPosition() float64 {
	if x != nil {
		return x.MaxPosition
	}
	return 0
}

// GetStatus 获取STATUS.
func (x *SetStrategyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SetStrategyResponse 表示SetStrategy响应结构体。
type SetStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"` // Strategy唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *SetStrategyResponse) Reset() {
	*x = SetStrategyResponse{}
	mi := &file_api_market_making_market_making_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *SetStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*SetStrategyResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *SetStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStrategyResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*SetStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{3}
}

// GetStrategyId 获取Strategy唯一标识.
func (x *SetStrategyResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// GetStrategyRequest 表示获取Strategy请求结构体。
type GetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetStrategyRequest) Reset() {
	*x = GetStrategyRequest{}
	mi := &file_api_market_making_market_making_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetStrategyRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{4}
}

// GetSymbol 获取交易对.
func (x *GetStrategyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetStrategyResponse 表示获取Strategy响应结构体。
type GetStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      *QuoteStrategy         `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // 策略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetStrategyResponse) Reset() {
	*x = GetStrategyResponse{}
	mi := &file_api_market_making_market_making_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetStrategyResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{5}
}

// GetStrategy 获取Strategy.
func (x *GetStrategyResponse) GetStrategy() *QuoteStrategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

// GetPerformanceRequest 表示获取Performance请求结构体。
type GetPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetPerformanceRequest) Reset() {
	*x = GetPerformanceRequest{}
	mi := &file_api_market_making_market_making_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetPerformanceRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{6}
}

// GetSymbol 获取交易对.
func (x *GetPerformanceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetStartTime 获取开始时间.
func (x *GetPerformanceRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// GetEndTime 获取结束时间.
func (x *GetPerformanceRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetPerformanceResponse 表示获取Performance响应结构体。
type GetPerformanceResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Performance   *MarketMakingPerformance `protobuf:"bytes,1,opt,name=performance,proto3" json:"performance,omitempty"` // 性能
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetPerformanceResponse) Reset() {
	*x = GetPerformanceResponse{}
	mi := &file_api_market_making_market_making_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetPerformanceResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_making_market_making_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_api_market_making_market_making_proto_rawDescGZIP(), []int{7}
}

// GetPerformance 获取Performance.
func (x *GetPerformanceResponse) GetPerformance() *MarketMakingPerformance {
	if x != nil {
		return x.Performance
	}
	return nil
}

var File_api_market_making_market_making_proto protoreflect.FileDescriptor

const file_api_market_making_market_making_proto_rawDesc = "" +
	"\n" +
	"%api/market-making/market_making.proto\x12\rmarket_making\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\rQuoteStrategy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06spread\x18\x03 \x01(\x01R\x06spread\x12$\n" +
	"\x0emin_order_size\x18\x04 \x01(\x01R\fminOrderSize\x12$\n" +
	"\x0emax_order_size\x18\x05 \x01(\x01R\fmaxOrderSize\x12!\n" +
	"\fmax_position\x18\x06 \x01(\x01R\vmaxPosition\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x02\n" +
	"\x17MarketMakingPerformance\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\ttotal_pnl\x18\x02 \x01(\x01R\btotalPnl\x12!\n" +
	"\ftotal_volume\x18\x03 \x01(\x01R\vtotalVolume\x12!\n" +
	"\ftotal_trades\x18\x04 \x01(\x05R\vtotalTrades\x12!\n" +
	"\fsharpe_ratio\x18\x05 \x01(\x01R\vsharpeRatio\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xcb\x01\n" +
	"\x12SetStrategyRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06spread\x18\x02 \x01(\x01R\x06spread\x12$\n" +
	"\x0emin_order_size\x18\x03 \x01(\x01R\fminOrderSize\x12$\n" +
	"\x0emax_order_size\x18\x04 \x01(\x01R\fmaxOrderSize\x12!\n" +
	"\fmax_position\x18\x05 \x01(\x01R\vmaxPosition\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"6\n" +
	"\x13SetStrategyResponse\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\",\n" +
	"\x12GetStrategyRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"O\n" +
	"\x13GetStrategyResponse\x128\n" +
	"\bstrategy\x18\x01 \x01(\v2\x1c.market_making.QuoteStrategyR\bstrategy\"\xa1\x01\n" +
	"\x15GetPerformanceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"b\n" +
	"\x16GetPerformanceResponse\x12H\n" +
	"\vperformance\x18\x01 \x01(\v2&.market_making.MarketMakingPerformanceR\vperformance2\xa0\x02\n" +
	"\x13MarketMakingService\x12T\n" +
	"\vSetStrategy\x12!.market_making.SetStrategyRequest\x1a\".market_making.SetStrategyResponse\x12T\n" +
	"\vGetStrategy\x12!.market_making.GetStrategyRequest\x1a\".market_making.GetStrategyResponse\x12]\n" +
	"\x0eGetPerformance\x12$.market_making.GetPerformanceRequest\x1a%.market_making.GetPerformanceResponseBGZEgithub.com/wyfcoding/financialTrading/go-api/market-making;market_makingb\x06proto3"

var (
	file_api_market_making_market_making_proto_rawDescOnce sync.Once
	file_api_market_making_market_making_proto_rawDescData []byte
)

func file_api_market_making_market_making_proto_rawDescGZIP() []byte {
	file_api_market_making_market_making_proto_rawDescOnce.Do(func() {
		file_api_market_making_market_making_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_market_making_market_making_proto_rawDesc), len(file_api_market_making_market_making_proto_rawDesc)))
	})
	return file_api_market_making_market_making_proto_rawDescData
}

var file_api_market_making_market_making_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_market_making_market_making_proto_goTypes = []any{
	(*QuoteStrategy)(nil),           // 0: market_making.QuoteStrategy
	(*MarketMakingPerformance)(nil), // 1: market_making.MarketMakingPerformance
	(*SetStrategyRequest)(nil),      // 2: market_making.SetStrategyRequest
	(*SetStrategyResponse)(nil),     // 3: market_making.SetStrategyResponse
	(*GetStrategyRequest)(nil),      // 4: market_making.GetStrategyRequest
	(*GetStrategyResponse)(nil),     // 5: market_making.GetStrategyResponse
	(*GetPerformanceRequest)(nil),   // 6: market_making.GetPerformanceRequest
	(*GetPerformanceResponse)(nil),  // 7: market_making.GetPerformanceResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_api_market_making_market_making_proto_depIdxs = []int32{
	8,  // 0: market_making.QuoteStrategy.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: market_making.QuoteStrategy.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: market_making.MarketMakingPerformance.start_time:type_name -> google.protobuf.Timestamp
	8,  // 3: market_making.MarketMakingPerformance.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: market_making.GetStrategyResponse.strategy:type_name -> market_making.QuoteStrategy
	8,  // 5: market_making.GetPerformanceRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 6: market_making.GetPerformanceRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 7: market_making.GetPerformanceResponse.performance:type_name -> market_making.MarketMakingPerformance
	2,  // 8: market_making.MarketMakingService.SetStrategy:input_type -> market_making.SetStrategyRequest
	4,  // 9: market_making.MarketMakingService.GetStrategy:input_type -> market_making.GetStrategyRequest
	6,  // 10: market_making.MarketMakingService.GetPerformance:input_type -> market_making.GetPerformanceRequest
	3,  // 11: market_making.MarketMakingService.SetStrategy:output_type -> market_making.SetStrategyResponse
	5,  // 12: market_making.MarketMakingService.GetStrategy:output_type -> market_making.GetStrategyResponse
	7,  // 13: market_making.MarketMakingService.GetPerformance:output_type -> market_making.GetPerformanceResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_market_making_market_making_proto_init() }
func file_api_market_making_market_making_proto_init() {
	if File_api_market_making_market_making_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_market_making_market_making_proto_rawDesc), len(file_api_market_making_market_making_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_market_making_market_making_proto_goTypes,
		DependencyIndexes: file_api_market_making_market_making_proto_depIdxs,
		MessageInfos:      file_api_market_making_market_making_proto_msgTypes,
	}.Build()
	File_api_market_making_market_making_proto = out.File // File_api_market_making_market_making_proto 文件API市场making市场makingProto
	file_api_market_making_market_making_proto_goTypes = nil
	file_api_market_making_market_making_proto_depIdxs = nil
}
