// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/market-making/market_making.proto

package market_making

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketMakingService_SetStrategy_FullMethodName    = "/market_making.MarketMakingService/SetStrategy" // MarketMakingService_SetStrategy_FullMethodName 市场MakingSERVICESetStrategyFullMethod名称
	MarketMakingService_GetStrategy_FullMethodName    = "/market_making.MarketMakingService/GetStrategy" // MarketMakingService_GetStrategy_FullMethodName 市场MakingSERVICE获取StrategyFullMethod名称
	MarketMakingService_GetPerformance_FullMethodName = "/market_making.MarketMakingService/GetPerformance" // MarketMakingService_GetPerformance_FullMethodName 市场MakingSERVICE获取PerformanceFullMethod名称
)

// MarketMakingServiceClient is the client API for MarketMakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketMakingService 提供做市策略管理服务
// MarketMakingServiceClient 表示市场MakingSERVICE客户端结构体。
type MarketMakingServiceClient interface {
	// 设置做市策略
	SetStrategy(ctx context.Context, in *SetStrategyRequest, opts ...grpc.CallOption) (*SetStrategyResponse, error)
	// 获取做市策略
	GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error)
	// 获取做市绩效
	GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error)
}

type marketMakingServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewMarketMakingServiceClient 创建新的创建一个新的实例市场MakingSERVICE客户端.
func NewMarketMakingServiceClient(cc grpc.ClientConnInterface) MarketMakingServiceClient {
	return &marketMakingServiceClient{cc}
}

// SetStrategy 执行SetStrategy逻辑。
func (c *marketMakingServiceClient) SetStrategy(ctx context.Context, in *SetStrategyRequest, opts ...grpc.CallOption) (*SetStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStrategyResponse)
	err := c.cc.Invoke(ctx, MarketMakingService_SetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStrategy 获取Strategy.
func (c *marketMakingServiceClient) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrategyResponse)
	err := c.cc.Invoke(ctx, MarketMakingService_GetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPerformance 获取Performance.
func (c *marketMakingServiceClient) GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPerformanceResponse)
	err := c.cc.Invoke(ctx, MarketMakingService_GetPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketMakingServiceServer is the server API for MarketMakingService service.
// All implementations must embed UnimplementedMarketMakingServiceServer
// for forward compatibility.
//
// MarketMakingService 提供做市策略管理服务
// MarketMakingServiceServer 表示市场MakingSERVICE服务端结构体。
type MarketMakingServiceServer interface {
	// 设置做市策略
	SetStrategy(context.Context, *SetStrategyRequest) (*SetStrategyResponse, error)
	// 获取做市策略
	GetStrategy(context.Context, *GetStrategyRequest) (*GetStrategyResponse, error)
	// 获取做市绩效
	GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error)
	mustEmbedUnimplementedMarketMakingServiceServer()
}

// UnimplementedMarketMakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedMarketMakingServiceServer 表示未实现的市场MakingSERVICE服务端结构体。
type UnimplementedMarketMakingServiceServer struct{}

// SetStrategy 执行SetStrategy逻辑。
func (UnimplementedMarketMakingServiceServer) SetStrategy(context.Context, *SetStrategyRequest) (*SetStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStrategy not implemented")
}
// GetStrategy 获取Strategy.
func (UnimplementedMarketMakingServiceServer) GetStrategy(context.Context, *GetStrategyRequest) (*GetStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategy not implemented")
}
// GetPerformance 获取Performance.
func (UnimplementedMarketMakingServiceServer) GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedMarketMakingServiceServer) mustEmbedUnimplementedMarketMakingServiceServer() {}
func (UnimplementedMarketMakingServiceServer) testEmbeddedByValue()                             {}

// UnsafeMarketMakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketMakingServiceServer will
// result in compilation errors.
// UnsafeMarketMakingServiceServer 表示Unsafe市场MakingSERVICE服务端结构体。
type UnsafeMarketMakingServiceServer interface {
	mustEmbedUnimplementedMarketMakingServiceServer()
}

// RegisterMarketMakingServiceServer 执行Register市场MakingSERVICE服务端逻辑。
func RegisterMarketMakingServiceServer(s grpc.ServiceRegistrar, srv MarketMakingServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketMakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketMakingService_ServiceDesc, srv)
}

func _MarketMakingService_SetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketMakingServiceServer).SetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketMakingService_SetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketMakingServiceServer).SetStrategy(ctx, req.(*SetStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketMakingService_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketMakingServiceServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketMakingService_GetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketMakingServiceServer).GetStrategy(ctx, req.(*GetStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketMakingService_GetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketMakingServiceServer).GetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketMakingService_GetPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketMakingServiceServer).GetPerformance(ctx, req.(*GetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketMakingService_ServiceDesc is the grpc.ServiceDesc for MarketMakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketMakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market_making.MarketMakingService",
	HandlerType: (*MarketMakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetStrategy",
			Handler:    _MarketMakingService_SetStrategy_Handler,
		},
		{
			MethodName: "GetStrategy",
			Handler:    _MarketMakingService_GetStrategy_Handler,
		},
		{
			MethodName: "GetPerformance",
			Handler:    _MarketMakingService_GetPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/market-making/market_making.proto",
}
