// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: execution/execution.proto

package execution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_ExecuteOrder_FullMethodName        = "/execution.ExecutionService/ExecuteOrder"
	ExecutionService_GetExecutionHistory_FullMethodName = "/execution.ExecutionService/GetExecutionHistory"
	ExecutionService_SubscribeExecutions_FullMethodName = "/execution.ExecutionService/SubscribeExecutions"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 交易执行服务，负责订单路由与撮合。
type ExecutionServiceClient interface {
	// 提交执行订单。
	ExecuteOrder(ctx context.Context, in *ExecuteOrderRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	// 获取历史成交。
	GetExecutionHistory(ctx context.Context, in *GetExecutionHistoryRequest, opts ...grpc.CallOption) (*ExecutionHistoryResponse, error)
	// 订阅实时成交流。
	SubscribeExecutions(ctx context.Context, in *SubscribeExecutionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionUpdate], error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) ExecuteOrder(ctx context.Context, in *ExecuteOrderRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ExecuteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetExecutionHistory(ctx context.Context, in *GetExecutionHistoryRequest, opts ...grpc.CallOption) (*ExecutionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionHistoryResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetExecutionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) SubscribeExecutions(ctx context.Context, in *SubscribeExecutionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[0], ExecutionService_SubscribeExecutions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeExecutionsRequest, ExecutionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_SubscribeExecutionsClient = grpc.ServerStreamingClient[ExecutionUpdate]

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// 交易执行服务，负责订单路由与撮合。
type ExecutionServiceServer interface {
	// 提交执行订单。
	ExecuteOrder(context.Context, *ExecuteOrderRequest) (*ExecutionResponse, error)
	// 获取历史成交。
	GetExecutionHistory(context.Context, *GetExecutionHistoryRequest) (*ExecutionHistoryResponse, error)
	// 订阅实时成交流。
	SubscribeExecutions(*SubscribeExecutionsRequest, grpc.ServerStreamingServer[ExecutionUpdate]) error
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) ExecuteOrder(context.Context, *ExecuteOrderRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteOrder not implemented")
}
func (UnimplementedExecutionServiceServer) GetExecutionHistory(context.Context, *GetExecutionHistoryRequest) (*ExecutionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionHistory not implemented")
}
func (UnimplementedExecutionServiceServer) SubscribeExecutions(*SubscribeExecutionsRequest, grpc.ServerStreamingServer[ExecutionUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeExecutions not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_ExecuteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ExecuteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ExecuteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ExecuteOrder(ctx, req.(*ExecuteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetExecutionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetExecutionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetExecutionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetExecutionHistory(ctx, req.(*GetExecutionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_SubscribeExecutions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeExecutionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutionServiceServer).SubscribeExecutions(m, &grpc.GenericServerStream[SubscribeExecutionsRequest, ExecutionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_SubscribeExecutionsServer = grpc.ServerStreamingServer[ExecutionUpdate]

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOrder",
			Handler:    _ExecutionService_ExecuteOrder_Handler,
		},
		{
			MethodName: "GetExecutionHistory",
			Handler:    _ExecutionService_GetExecutionHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeExecutions",
			Handler:       _ExecutionService_SubscribeExecutions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "execution/execution.proto",
}
