// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/execution/execution.proto

package execution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOrderRequest) Reset() {
	*x = ExecuteOrderRequest{}
	mi := &file_api_execution_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOrderRequest) ProtoMessage() {}

func (x *ExecuteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOrderRequest.ProtoReflect.Descriptor instead.
func (*ExecuteOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecuteOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExecuteOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *ExecuteOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ExecuteOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type ExecutionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExecutedQuantity string                 `protobuf:"bytes,4,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	ExecutedPrice    string                 `protobuf:"bytes,5,opt,name=executed_price,json=executedPrice,proto3" json:"executed_price,omitempty"`
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_api_execution_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionResponse) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *ExecutionResponse) GetExecutedPrice() string {
	if x != nil {
		return x.ExecutedPrice
	}
	return ""
}

func (x *ExecutionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetExecutionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionHistoryRequest) Reset() {
	*x = GetExecutionHistoryRequest{}
	mi := &file_api_execution_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionHistoryRequest) ProtoMessage() {}

func (x *GetExecutionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{2}
}

func (x *GetExecutionHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExecutionHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetExecutionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ExecutionRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ExecutedQuantity string                 `protobuf:"bytes,4,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	ExecutedPrice    string                 `protobuf:"bytes,5,opt,name=executed_price,json=executedPrice,proto3" json:"executed_price,omitempty"`
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_api_execution_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionRecord) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionRecord) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecutionRecord) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExecutionRecord) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *ExecutionRecord) GetExecutedPrice() string {
	if x != nil {
		return x.ExecutedPrice
	}
	return ""
}

func (x *ExecutionRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ExecutionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionRecord     `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionHistoryResponse) Reset() {
	*x = ExecutionHistoryResponse{}
	mi := &file_api_execution_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionHistoryResponse) ProtoMessage() {}

func (x *ExecutionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionHistoryResponse.ProtoReflect.Descriptor instead.
func (*ExecutionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionHistoryResponse) GetExecutions() []*ExecutionRecord {
	if x != nil {
		return x.Executions
	}
	return nil
}

type SubscribeExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeExecutionsRequest) Reset() {
	*x = SubscribeExecutionsRequest{}
	mi := &file_api_execution_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeExecutionsRequest) ProtoMessage() {}

func (x *SubscribeExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeExecutionsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeExecutionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExecutionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionUpdate) Reset() {
	*x = ExecutionUpdate{}
	mi := &file_api_execution_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionUpdate) ProtoMessage() {}

func (x *ExecutionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_execution_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionUpdate.ProtoReflect.Descriptor instead.
func (*ExecutionUpdate) Descriptor() ([]byte, []int) {
	return file_api_execution_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionUpdate) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecutionUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_execution_execution_proto protoreflect.FileDescriptor

const file_api_execution_execution_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/execution/execution.proto\x12\texecution\"\xa7\x01\n" +
	"\x13ExecuteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\"\x80\x02\n" +
	"\x11ExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x11executed_quantity\x18\x04 \x01(\tR\x10executedQuantity\x12%\n" +
	"\x0eexecuted_price\x18\x05 \x01(\tR\rexecutedPrice\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"c\n" +
	"\x1aGetExecutionHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xd9\x01\n" +
	"\x0fExecutionRecord\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12+\n" +
	"\x11executed_quantity\x18\x04 \x01(\tR\x10executedQuantity\x12%\n" +
	"\x0eexecuted_price\x18\x05 \x01(\tR\rexecutedPrice\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"V\n" +
	"\x18ExecutionHistoryResponse\x12:\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1a.execution.ExecutionRecordR\n" +
	"executions\"5\n" +
	"\x1aSubscribeExecutionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x85\x01\n" +
	"\x0fExecutionUpdate\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x9f\x02\n" +
	"\x10ExecutionService\x12L\n" +
	"\fExecuteOrder\x12\x1e.execution.ExecuteOrderRequest\x1a\x1c.execution.ExecutionResponse\x12a\n" +
	"\x13GetExecutionHistory\x12%.execution.GetExecutionHistoryRequest\x1a#.execution.ExecutionHistoryResponse\x12Z\n" +
	"\x13SubscribeExecutions\x12%.execution.SubscribeExecutionsRequest\x1a\x1a.execution.ExecutionUpdate0\x01B?Z=github.com/wyfcoding/financialTrading/go-api/execution;executionb\x06proto3"

var (
	file_api_execution_execution_proto_rawDescOnce sync.Once
	file_api_execution_execution_proto_rawDescData []byte
)

func file_api_execution_execution_proto_rawDescGZIP() []byte {
	file_api_execution_execution_proto_rawDescOnce.Do(func() {
		file_api_execution_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_execution_execution_proto_rawDesc), len(file_api_execution_execution_proto_rawDesc)))
	})
	return file_api_execution_execution_proto_rawDescData
}

var file_api_execution_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_execution_execution_proto_goTypes = []any{
	(*ExecuteOrderRequest)(nil),        // 0: execution.ExecuteOrderRequest
	(*ExecutionResponse)(nil),          // 1: execution.ExecutionResponse
	(*GetExecutionHistoryRequest)(nil), // 2: execution.GetExecutionHistoryRequest
	(*ExecutionRecord)(nil),            // 3: execution.ExecutionRecord
	(*ExecutionHistoryResponse)(nil),   // 4: execution.ExecutionHistoryResponse
	(*SubscribeExecutionsRequest)(nil), // 5: execution.SubscribeExecutionsRequest
	(*ExecutionUpdate)(nil),            // 6: execution.ExecutionUpdate
}
var file_api_execution_execution_proto_depIdxs = []int32{
	3, // 0: execution.ExecutionHistoryResponse.executions:type_name -> execution.ExecutionRecord
	0, // 1: execution.ExecutionService.ExecuteOrder:input_type -> execution.ExecuteOrderRequest
	2, // 2: execution.ExecutionService.GetExecutionHistory:input_type -> execution.GetExecutionHistoryRequest
	5, // 3: execution.ExecutionService.SubscribeExecutions:input_type -> execution.SubscribeExecutionsRequest
	1, // 4: execution.ExecutionService.ExecuteOrder:output_type -> execution.ExecutionResponse
	4, // 5: execution.ExecutionService.GetExecutionHistory:output_type -> execution.ExecutionHistoryResponse
	6, // 6: execution.ExecutionService.SubscribeExecutions:output_type -> execution.ExecutionUpdate
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_execution_execution_proto_init() }
func file_api_execution_execution_proto_init() {
	if File_api_execution_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_execution_execution_proto_rawDesc), len(file_api_execution_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_execution_execution_proto_goTypes,
		DependencyIndexes: file_api_execution_execution_proto_depIdxs,
		MessageInfos:      file_api_execution_execution_proto_msgTypes,
	}.Build()
	File_api_execution_execution_proto = out.File
	file_api_execution_execution_proto_goTypes = nil
	file_api_execution_execution_proto_depIdxs = nil
}
