// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/market-data/market_data.proto

package market_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取最新行情请求
// GetLatestQuoteRequest 表示获取LatestQuote请求结构体。
type GetLatestQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetLatestQuoteRequest) Reset() {
	*x = GetLatestQuoteRequest{}
	mi := &file_api_market_data_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetLatestQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetLatestQuoteRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetLatestQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestQuoteRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetLatestQuoteRequest) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{0}
}

// GetSymbol 获取交易对.
func (x *GetLatestQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// 行情响应
// QuoteResponse 表示Quote响应结构体。
type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	BidPrice      float64                `protobuf:"fixed64,2,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"` // Bid价格
	AskPrice      float64                `protobuf:"fixed64,3,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"` // Ask价格
	BidSize       float64                `protobuf:"fixed64,4,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"` // Bid大小
	AskSize       float64                `protobuf:"fixed64,5,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"` // Ask大小
	LastPrice     float64                `protobuf:"fixed64,6,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"` // 最后价格
	LastSize      float64                `protobuf:"fixed64,7,opt,name=last_size,json=lastSize,proto3" json:"last_size,omitempty"` // 最后大小
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_api_market_data_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*QuoteResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{1}
}

// GetSymbol 获取交易对.
func (x *QuoteResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetBidPrice 获取Bid价格.
func (x *QuoteResponse) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

// GetAskPrice 获取Ask价格.
func (x *QuoteResponse) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

// GetBidSize 获取Bid大小.
func (x *QuoteResponse) GetBidSize() float64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

// GetAskSize 获取Ask大小.
func (x *QuoteResponse) GetAskSize() float64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

// GetLastPrice 获取最后价格.
func (x *QuoteResponse) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

// GetLastSize 获取最后大小.
func (x *QuoteResponse) GetLastSize() float64 {
	if x != nil {
		return x.LastSize
	}
	return 0
}

// GetTimestamp 获取Timestamp.
func (x *QuoteResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 获取 K 线请求
// GetKlinesRequest 表示获取Klines请求结构体。
type GetKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"` // Interval
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetKlinesRequest) Reset() {
	*x = GetKlinesRequest{}
	mi := &file_api_market_data_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetKlinesRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetKlinesRequest) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{2}
}

// GetSymbol 获取交易对.
func (x *GetKlinesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetInterval 获取Interval.
func (x *GetKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

// GetLimit 获取限制.
func (x *GetKlinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// K 线数据
// Kline 表示Kline结构体。
type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTime      int64                  `protobuf:"varint,1,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"` // 打开时间
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"` // 打开
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"` // 高
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"` // 低
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"` // 关闭
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"` // Volume
	CloseTime     int64                  `protobuf:"varint,7,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"` // 关闭时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_api_market_data_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*Kline) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*Kline) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{3}
}

// GetOpenTime 获取打开时间.
func (x *Kline) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

// GetOpen 获取打开.
func (x *Kline) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

// GetHigh 获取High.
func (x *Kline) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

// GetLow 获取Low.
func (x *Kline) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

// GetClose 获取关闭.
func (x *Kline) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

// GetVolume 获取VOLUME.
func (x *Kline) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// GetCloseTime 获取关闭时间.
func (x *Kline) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

// K 线响应
// KlinesResponse 表示Klines响应结构体。
type KlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"` // Interval
	Klines        []*Kline               `protobuf:"bytes,3,rep,name=klines,proto3" json:"klines,omitempty"` // Klines
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *KlinesResponse) Reset() {
	*x = KlinesResponse{}
	mi := &file_api_market_data_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *KlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*KlinesResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *KlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KlinesResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*KlinesResponse) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{4}
}

// GetSymbol 获取交易对.
func (x *KlinesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetInterval 获取Interval.
func (x *KlinesResponse) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

// GetKlines 获取Klines.
func (x *KlinesResponse) GetKlines() []*Kline {
	if x != nil {
		return x.Klines
	}
	return nil
}

// 获取订单簿请求
// GetOrderBookRequest 表示获取订单Book请求结构体。
type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // 默认 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_api_market_data_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetOrderBookRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{5}
}

// GetSymbol 获取交易对.
func (x *GetOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetDepth 获取Depth.
func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// 订单簿层级
// OrderBookLevel 表示订单Book等级结构体。
type OrderBookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"` // 价格
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *OrderBookLevel) Reset() {
	*x = OrderBookLevel{}
	mi := &file_api_market_data_market_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *OrderBookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*OrderBookLevel) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *OrderBookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookLevel.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*OrderBookLevel) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{6}
}

// GetPrice 获取价格.
func (x *OrderBookLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetQuantity 获取数量.
func (x *OrderBookLevel) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 订单簿响应
// OrderBookResponse 表示订单Book响应结构体。
type OrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Bids          []*OrderBookLevel      `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"` // Bids
	Asks          []*OrderBookLevel      `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"` // Asks
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *OrderBookResponse) Reset() {
	*x = OrderBookResponse{}
	mi := &file_api_market_data_market_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *OrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*OrderBookResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *OrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{7}
}

// GetSymbol 获取交易对.
func (x *OrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetBids 获取Bids.
func (x *OrderBookResponse) GetBids() []*OrderBookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

// GetAsks 获取Asks.
func (x *OrderBookResponse) GetAsks() []*OrderBookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// GetTimestamp 获取Timestamp.
func (x *OrderBookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 订阅行情请求
// SubscribeQuotesRequest 表示SubscribeQuotes请求结构体。
type SubscribeQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // Symbols
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *SubscribeQuotesRequest) Reset() {
	*x = SubscribeQuotesRequest{}
	mi := &file_api_market_data_market_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *SubscribeQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*SubscribeQuotesRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *SubscribeQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeQuotesRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*SubscribeQuotesRequest) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{8}
}

// GetSymbols 获取Symbols.
func (x *SubscribeQuotesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// 行情更新
// QuoteUpdate 表示Quote更新结构体。
type QuoteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	BidPrice      float64                `protobuf:"fixed64,2,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"` // Bid价格
	AskPrice      float64                `protobuf:"fixed64,3,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"` // Ask价格
	BidSize       float64                `protobuf:"fixed64,4,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"` // Bid大小
	AskSize       float64                `protobuf:"fixed64,5,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"` // Ask大小
	LastPrice     float64                `protobuf:"fixed64,6,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"` // 最后价格
	LastSize      float64                `protobuf:"fixed64,7,opt,name=last_size,json=lastSize,proto3" json:"last_size,omitempty"` // 最后大小
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *QuoteUpdate) Reset() {
	*x = QuoteUpdate{}
	mi := &file_api_market_data_market_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *QuoteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*QuoteUpdate) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *QuoteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteUpdate.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*QuoteUpdate) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{9}
}

// GetSymbol 获取交易对.
func (x *QuoteUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetBidPrice 获取Bid价格.
func (x *QuoteUpdate) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

// GetAskPrice 获取Ask价格.
func (x *QuoteUpdate) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

// GetBidSize 获取Bid大小.
func (x *QuoteUpdate) GetBidSize() float64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

// GetAskSize 获取Ask大小.
func (x *QuoteUpdate) GetAskSize() float64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

// GetLastPrice 获取最后价格.
func (x *QuoteUpdate) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

// GetLastSize 获取最后大小.
func (x *QuoteUpdate) GetLastSize() float64 {
	if x != nil {
		return x.LastSize
	}
	return 0
}

// GetTimestamp 获取Timestamp.
func (x *QuoteUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 获取交易历史请求
// GetTradesRequest 表示获取Trades请求结构体。
type GetTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *GetTradesRequest) Reset() {
	*x = GetTradesRequest{}
	mi := &file_api_market_data_market_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *GetTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*GetTradesRequest) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *GetTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesRequest.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{10}
}

// GetSymbol 获取交易对.
func (x *GetTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetLimit 获取限制.
func (x *GetTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 交易记录
// TradeRecord 表示成交Record结构体。
type TradeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // 成交唯一标识
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` // 价格
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // 数量
	Side          string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"` // 方向
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *TradeRecord) Reset() {
	*x = TradeRecord{}
	mi := &file_api_market_data_market_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *TradeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*TradeRecord) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *TradeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRecord.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*TradeRecord) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{11}
}

// GetTradeId 获取成交唯一标识.
func (x *TradeRecord) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// GetSymbol 获取交易对.
func (x *TradeRecord) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetPrice 获取价格.
func (x *TradeRecord) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetQuantity 获取数量.
func (x *TradeRecord) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// GetSide 获取交易方向.
func (x *TradeRecord) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

// GetTimestamp 获取Timestamp.
func (x *TradeRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 交易历史响应
// TradesResponse 表示Trades响应结构体。
type TradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对
	Trades        []*TradeRecord         `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"` // Trades
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset 执行重置逻辑。
func (x *TradesResponse) Reset() {
	*x = TradesResponse{}
	mi := &file_api_market_data_market_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String 字符串表示。
func (x *TradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage 执行Proto消息逻辑。
func (*TradesResponse) ProtoMessage() {}

// ProtoReflect 执行ProtoReflect逻辑。
func (x *TradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_market_data_market_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradesResponse.ProtoReflect.Descriptor instead.
// Descriptor 执行Descriptor逻辑。
func (*TradesResponse) Descriptor() ([]byte, []int) {
	return file_api_market_data_market_data_proto_rawDescGZIP(), []int{12}
}

// GetSymbol 获取交易对.
func (x *TradesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetTrades 获取Trades.
func (x *TradesResponse) GetTrades() []*TradeRecord {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_api_market_data_market_data_proto protoreflect.FileDescriptor

const file_api_market_data_market_data_proto_rawDesc = "" +
	"\n" +
	"!api/market-data/market_data.proto\x12\vmarket_data\"/\n" +
	"\x15GetLatestQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf1\x01\n" +
	"\rQuoteResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tbid_price\x18\x02 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\task_price\x18\x03 \x01(\x01R\baskPrice\x12\x19\n" +
	"\bbid_size\x18\x04 \x01(\x01R\abidSize\x12\x19\n" +
	"\bask_size\x18\x05 \x01(\x01R\aaskSize\x12\x1d\n" +
	"\n" +
	"last_price\x18\x06 \x01(\x01R\tlastPrice\x12\x1b\n" +
	"\tlast_size\x18\a \x01(\x01R\blastSize\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\\\n" +
	"\x10GetKlinesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xab\x01\n" +
	"\x05Kline\x12\x1b\n" +
	"\topen_time\x18\x01 \x01(\x03R\bopenTime\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"close_time\x18\a \x01(\x03R\tcloseTime\"p\n" +
	"\x0eKlinesResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12*\n" +
	"\x06klines\x18\x03 \x03(\v2\x12.market_data.KlineR\x06klines\"C\n" +
	"\x13GetOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"B\n" +
	"\x0eOrderBookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\xab\x01\n" +
	"\x11OrderBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12/\n" +
	"\x04bids\x18\x02 \x03(\v2\x1b.market_data.OrderBookLevelR\x04bids\x12/\n" +
	"\x04asks\x18\x03 \x03(\v2\x1b.market_data.OrderBookLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"2\n" +
	"\x16SubscribeQuotesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xef\x01\n" +
	"\vQuoteUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tbid_price\x18\x02 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\task_price\x18\x03 \x01(\x01R\baskPrice\x12\x19\n" +
	"\bbid_size\x18\x04 \x01(\x01R\abidSize\x12\x19\n" +
	"\bask_size\x18\x05 \x01(\x01R\aaskSize\x12\x1d\n" +
	"\n" +
	"last_price\x18\x06 \x01(\x01R\tlastPrice\x12\x1b\n" +
	"\tlast_size\x18\a \x01(\x01R\blastSize\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"@\n" +
	"\x10GetTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa4\x01\n" +
	"\vTradeRecord\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"Z\n" +
	"\x0eTradesResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x120\n" +
	"\x06trades\x18\x02 \x03(\v2\x18.market_data.TradeRecordR\x06trades2\x9d\x03\n" +
	"\x11MarketDataService\x12P\n" +
	"\x0eGetLatestQuote\x12\".market_data.GetLatestQuoteRequest\x1a\x1a.market_data.QuoteResponse\x12G\n" +
	"\tGetKlines\x12\x1d.market_data.GetKlinesRequest\x1a\x1b.market_data.KlinesResponse\x12P\n" +
	"\fGetOrderBook\x12 .market_data.GetOrderBookRequest\x1a\x1e.market_data.OrderBookResponse\x12R\n" +
	"\x0fSubscribeQuotes\x12#.market_data.SubscribeQuotesRequest\x1a\x18.market_data.QuoteUpdate0\x01\x12G\n" +
	"\tGetTrades\x12\x1d.market_data.GetTradesRequest\x1a\x1b.market_data.TradesResponseBCZAgithub.com/wyfcoding/financialTrading/go-api/market-data;market_datab\x06proto3"

var (
	file_api_market_data_market_data_proto_rawDescOnce sync.Once
	file_api_market_data_market_data_proto_rawDescData []byte
)

func file_api_market_data_market_data_proto_rawDescGZIP() []byte {
	file_api_market_data_market_data_proto_rawDescOnce.Do(func() {
		file_api_market_data_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_market_data_market_data_proto_rawDesc), len(file_api_market_data_market_data_proto_rawDesc)))
	})
	return file_api_market_data_market_data_proto_rawDescData
}

var file_api_market_data_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_market_data_market_data_proto_goTypes = []any{
	(*GetLatestQuoteRequest)(nil),  // 0: market_data.GetLatestQuoteRequest
	(*QuoteResponse)(nil),          // 1: market_data.QuoteResponse
	(*GetKlinesRequest)(nil),       // 2: market_data.GetKlinesRequest
	(*Kline)(nil),                  // 3: market_data.Kline
	(*KlinesResponse)(nil),         // 4: market_data.KlinesResponse
	(*GetOrderBookRequest)(nil),    // 5: market_data.GetOrderBookRequest
	(*OrderBookLevel)(nil),         // 6: market_data.OrderBookLevel
	(*OrderBookResponse)(nil),      // 7: market_data.OrderBookResponse
	(*SubscribeQuotesRequest)(nil), // 8: market_data.SubscribeQuotesRequest
	(*QuoteUpdate)(nil),            // 9: market_data.QuoteUpdate
	(*GetTradesRequest)(nil),       // 10: market_data.GetTradesRequest
	(*TradeRecord)(nil),            // 11: market_data.TradeRecord
	(*TradesResponse)(nil),         // 12: market_data.TradesResponse
}
var file_api_market_data_market_data_proto_depIdxs = []int32{
	3,  // 0: market_data.KlinesResponse.klines:type_name -> market_data.Kline
	6,  // 1: market_data.OrderBookResponse.bids:type_name -> market_data.OrderBookLevel
	6,  // 2: market_data.OrderBookResponse.asks:type_name -> market_data.OrderBookLevel
	11, // 3: market_data.TradesResponse.trades:type_name -> market_data.TradeRecord
	0,  // 4: market_data.MarketDataService.GetLatestQuote:input_type -> market_data.GetLatestQuoteRequest
	2,  // 5: market_data.MarketDataService.GetKlines:input_type -> market_data.GetKlinesRequest
	5,  // 6: market_data.MarketDataService.GetOrderBook:input_type -> market_data.GetOrderBookRequest
	8,  // 7: market_data.MarketDataService.SubscribeQuotes:input_type -> market_data.SubscribeQuotesRequest
	10, // 8: market_data.MarketDataService.GetTrades:input_type -> market_data.GetTradesRequest
	1,  // 9: market_data.MarketDataService.GetLatestQuote:output_type -> market_data.QuoteResponse
	4,  // 10: market_data.MarketDataService.GetKlines:output_type -> market_data.KlinesResponse
	7,  // 11: market_data.MarketDataService.GetOrderBook:output_type -> market_data.OrderBookResponse
	9,  // 12: market_data.MarketDataService.SubscribeQuotes:output_type -> market_data.QuoteUpdate
	12, // 13: market_data.MarketDataService.GetTrades:output_type -> market_data.TradesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_market_data_market_data_proto_init() }
func file_api_market_data_market_data_proto_init() {
	if File_api_market_data_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_market_data_market_data_proto_rawDesc), len(file_api_market_data_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_market_data_market_data_proto_goTypes,
		DependencyIndexes: file_api_market_data_market_data_proto_depIdxs,
		MessageInfos:      file_api_market_data_market_data_proto_msgTypes,
	}.Build()
	File_api_market_data_market_data_proto = out.File // File_api_market_data_market_data_proto 文件API市场DATA市场DATAProto
	file_api_market_data_market_data_proto_goTypes = nil
	file_api_market_data_market_data_proto_depIdxs = nil
}
