// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/pricing/pricing.proto

package pricing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // CALL, PUT
	StrikePrice   float64                `protobuf:"fixed64,3,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionContract) Reset() {
	*x = OptionContract{}
	mi := &file_api_pricing_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionContract) ProtoMessage() {}

func (x *OptionContract) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionContract.ProtoReflect.Descriptor instead.
func (*OptionContract) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *OptionContract) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OptionContract) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OptionContract) GetStrikePrice() float64 {
	if x != nil {
		return x.StrikePrice
	}
	return 0
}

func (x *OptionContract) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

type Greeks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         float64                `protobuf:"fixed64,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Gamma         float64                `protobuf:"fixed64,2,opt,name=gamma,proto3" json:"gamma,omitempty"`
	Theta         float64                `protobuf:"fixed64,3,opt,name=theta,proto3" json:"theta,omitempty"`
	Vega          float64                `protobuf:"fixed64,4,opt,name=vega,proto3" json:"vega,omitempty"`
	Rho           float64                `protobuf:"fixed64,5,opt,name=rho,proto3" json:"rho,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Greeks) Reset() {
	*x = Greeks{}
	mi := &file_api_pricing_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Greeks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeks) ProtoMessage() {}

func (x *Greeks) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeks.ProtoReflect.Descriptor instead.
func (*Greeks) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *Greeks) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Greeks) GetGamma() float64 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *Greeks) GetTheta() float64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

func (x *Greeks) GetVega() float64 {
	if x != nil {
		return x.Vega
	}
	return 0
}

func (x *Greeks) GetRho() float64 {
	if x != nil {
		return x.Rho
	}
	return 0
}

type GetOptionPriceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Contract        *OptionContract        `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	UnderlyingPrice float64                `protobuf:"fixed64,2,opt,name=underlying_price,json=underlyingPrice,proto3" json:"underlying_price,omitempty"`
	Volatility      float64                `protobuf:"fixed64,3,opt,name=volatility,proto3" json:"volatility,omitempty"`
	RiskFreeRate    float64                `protobuf:"fixed64,4,opt,name=risk_free_rate,json=riskFreeRate,proto3" json:"risk_free_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOptionPriceRequest) Reset() {
	*x = GetOptionPriceRequest{}
	mi := &file_api_pricing_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptionPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptionPriceRequest) ProtoMessage() {}

func (x *GetOptionPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptionPriceRequest.ProtoReflect.Descriptor instead.
func (*GetOptionPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *GetOptionPriceRequest) GetContract() *OptionContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetOptionPriceRequest) GetUnderlyingPrice() float64 {
	if x != nil {
		return x.UnderlyingPrice
	}
	return 0
}

func (x *GetOptionPriceRequest) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *GetOptionPriceRequest) GetRiskFreeRate() float64 {
	if x != nil {
		return x.RiskFreeRate
	}
	return 0
}

type GetOptionPriceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Price           float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	CalculationTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=calculation_time,json=calculationTime,proto3" json:"calculation_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOptionPriceResponse) Reset() {
	*x = GetOptionPriceResponse{}
	mi := &file_api_pricing_pricing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptionPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptionPriceResponse) ProtoMessage() {}

func (x *GetOptionPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptionPriceResponse.ProtoReflect.Descriptor instead.
func (*GetOptionPriceResponse) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{3}
}

func (x *GetOptionPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetOptionPriceResponse) GetCalculationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculationTime
	}
	return nil
}

type GetGreeksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Contract        *OptionContract        `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	UnderlyingPrice float64                `protobuf:"fixed64,2,opt,name=underlying_price,json=underlyingPrice,proto3" json:"underlying_price,omitempty"`
	Volatility      float64                `protobuf:"fixed64,3,opt,name=volatility,proto3" json:"volatility,omitempty"`
	RiskFreeRate    float64                `protobuf:"fixed64,4,opt,name=risk_free_rate,json=riskFreeRate,proto3" json:"risk_free_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGreeksRequest) Reset() {
	*x = GetGreeksRequest{}
	mi := &file_api_pricing_pricing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreeksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeksRequest) ProtoMessage() {}

func (x *GetGreeksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeksRequest.ProtoReflect.Descriptor instead.
func (*GetGreeksRequest) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{4}
}

func (x *GetGreeksRequest) GetContract() *OptionContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetGreeksRequest) GetUnderlyingPrice() float64 {
	if x != nil {
		return x.UnderlyingPrice
	}
	return 0
}

func (x *GetGreeksRequest) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *GetGreeksRequest) GetRiskFreeRate() float64 {
	if x != nil {
		return x.RiskFreeRate
	}
	return 0
}

type GetGreeksResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Greeks          *Greeks                `protobuf:"bytes,1,opt,name=greeks,proto3" json:"greeks,omitempty"`
	CalculationTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=calculation_time,json=calculationTime,proto3" json:"calculation_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGreeksResponse) Reset() {
	*x = GetGreeksResponse{}
	mi := &file_api_pricing_pricing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreeksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeksResponse) ProtoMessage() {}

func (x *GetGreeksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pricing_pricing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeksResponse.ProtoReflect.Descriptor instead.
func (*GetGreeksResponse) Descriptor() ([]byte, []int) {
	return file_api_pricing_pricing_proto_rawDescGZIP(), []int{5}
}

func (x *GetGreeksResponse) GetGreeks() *Greeks {
	if x != nil {
		return x.Greeks
	}
	return nil
}

func (x *GetGreeksResponse) GetCalculationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculationTime
	}
	return nil
}

var File_api_pricing_pricing_proto protoreflect.FileDescriptor

const file_api_pricing_pricing_proto_rawDesc = "" +
	"\n" +
	"\x19api/pricing/pricing.proto\x12\apricing\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x0eOptionContract\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fstrike_price\x18\x03 \x01(\x01R\vstrikePrice\x12;\n" +
	"\vexpiry_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"p\n" +
	"\x06Greeks\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x01R\x05delta\x12\x14\n" +
	"\x05gamma\x18\x02 \x01(\x01R\x05gamma\x12\x14\n" +
	"\x05theta\x18\x03 \x01(\x01R\x05theta\x12\x12\n" +
	"\x04vega\x18\x04 \x01(\x01R\x04vega\x12\x10\n" +
	"\x03rho\x18\x05 \x01(\x01R\x03rho\"\xbd\x01\n" +
	"\x15GetOptionPriceRequest\x123\n" +
	"\bcontract\x18\x01 \x01(\v2\x17.pricing.OptionContractR\bcontract\x12)\n" +
	"\x10underlying_price\x18\x02 \x01(\x01R\x0funderlyingPrice\x12\x1e\n" +
	"\n" +
	"volatility\x18\x03 \x01(\x01R\n" +
	"volatility\x12$\n" +
	"\x0erisk_free_rate\x18\x04 \x01(\x01R\friskFreeRate\"u\n" +
	"\x16GetOptionPriceResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12E\n" +
	"\x10calculation_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcalculationTime\"\xb8\x01\n" +
	"\x10GetGreeksRequest\x123\n" +
	"\bcontract\x18\x01 \x01(\v2\x17.pricing.OptionContractR\bcontract\x12)\n" +
	"\x10underlying_price\x18\x02 \x01(\x01R\x0funderlyingPrice\x12\x1e\n" +
	"\n" +
	"volatility\x18\x03 \x01(\x01R\n" +
	"volatility\x12$\n" +
	"\x0erisk_free_rate\x18\x04 \x01(\x01R\friskFreeRate\"\x83\x01\n" +
	"\x11GetGreeksResponse\x12'\n" +
	"\x06greeks\x18\x01 \x01(\v2\x0f.pricing.GreeksR\x06greeks\x12E\n" +
	"\x10calculation_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcalculationTime2\xa7\x01\n" +
	"\x0ePricingService\x12Q\n" +
	"\x0eGetOptionPrice\x12\x1e.pricing.GetOptionPriceRequest\x1a\x1f.pricing.GetOptionPriceResponse\x12B\n" +
	"\tGetGreeks\x12\x19.pricing.GetGreeksRequest\x1a\x1a.pricing.GetGreeksResponseB;Z9github.com/fynnwu/FinancialTrading/go-api/pricing;pricingb\x06proto3"

var (
	file_api_pricing_pricing_proto_rawDescOnce sync.Once
	file_api_pricing_pricing_proto_rawDescData []byte
)

func file_api_pricing_pricing_proto_rawDescGZIP() []byte {
	file_api_pricing_pricing_proto_rawDescOnce.Do(func() {
		file_api_pricing_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pricing_pricing_proto_rawDesc), len(file_api_pricing_pricing_proto_rawDesc)))
	})
	return file_api_pricing_pricing_proto_rawDescData
}

var file_api_pricing_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_pricing_pricing_proto_goTypes = []any{
	(*OptionContract)(nil),         // 0: pricing.OptionContract
	(*Greeks)(nil),                 // 1: pricing.Greeks
	(*GetOptionPriceRequest)(nil),  // 2: pricing.GetOptionPriceRequest
	(*GetOptionPriceResponse)(nil), // 3: pricing.GetOptionPriceResponse
	(*GetGreeksRequest)(nil),       // 4: pricing.GetGreeksRequest
	(*GetGreeksResponse)(nil),      // 5: pricing.GetGreeksResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_api_pricing_pricing_proto_depIdxs = []int32{
	6, // 0: pricing.OptionContract.expiry_date:type_name -> google.protobuf.Timestamp
	0, // 1: pricing.GetOptionPriceRequest.contract:type_name -> pricing.OptionContract
	6, // 2: pricing.GetOptionPriceResponse.calculation_time:type_name -> google.protobuf.Timestamp
	0, // 3: pricing.GetGreeksRequest.contract:type_name -> pricing.OptionContract
	1, // 4: pricing.GetGreeksResponse.greeks:type_name -> pricing.Greeks
	6, // 5: pricing.GetGreeksResponse.calculation_time:type_name -> google.protobuf.Timestamp
	2, // 6: pricing.PricingService.GetOptionPrice:input_type -> pricing.GetOptionPriceRequest
	4, // 7: pricing.PricingService.GetGreeks:input_type -> pricing.GetGreeksRequest
	3, // 8: pricing.PricingService.GetOptionPrice:output_type -> pricing.GetOptionPriceResponse
	5, // 9: pricing.PricingService.GetGreeks:output_type -> pricing.GetGreeksResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_pricing_pricing_proto_init() }
func file_api_pricing_pricing_proto_init() {
	if File_api_pricing_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pricing_pricing_proto_rawDesc), len(file_api_pricing_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pricing_pricing_proto_goTypes,
		DependencyIndexes: file_api_pricing_pricing_proto_depIdxs,
		MessageInfos:      file_api_pricing_pricing_proto_msgTypes,
	}.Build()
	File_api_pricing_pricing_proto = out.File
	file_api_pricing_pricing_proto_goTypes = nil
	file_api_pricing_pricing_proto_depIdxs = nil
}
