// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pricing/pricing.proto

package pricing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PricingService_GetOptionPrice_FullMethodName = "/pricing.PricingService/GetOptionPrice"
	PricingService_GetGreeks_FullMethodName      = "/pricing.PricingService/GetGreeks"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 期权定价服务，负责理论价格计算及希腊字母风险指标提取。
type PricingServiceClient interface {
	// 计算期权理论价值。
	GetOptionPrice(ctx context.Context, in *GetOptionPriceRequest, opts ...grpc.CallOption) (*GetOptionPriceResponse, error)
	// 计算期权的 Delta, Gamma, Theta, Vega, Rho 等指标。
	GetGreeks(ctx context.Context, in *GetGreeksRequest, opts ...grpc.CallOption) (*GetGreeksResponse, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) GetOptionPrice(ctx context.Context, in *GetOptionPriceRequest, opts ...grpc.CallOption) (*GetOptionPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOptionPriceResponse)
	err := c.cc.Invoke(ctx, PricingService_GetOptionPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetGreeks(ctx context.Context, in *GetGreeksRequest, opts ...grpc.CallOption) (*GetGreeksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGreeksResponse)
	err := c.cc.Invoke(ctx, PricingService_GetGreeks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility.
//
// 期权定价服务，负责理论价格计算及希腊字母风险指标提取。
type PricingServiceServer interface {
	// 计算期权理论价值。
	GetOptionPrice(context.Context, *GetOptionPriceRequest) (*GetOptionPriceResponse, error)
	// 计算期权的 Delta, Gamma, Theta, Vega, Rho 等指标。
	GetGreeks(context.Context, *GetGreeksRequest) (*GetGreeksResponse, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPricingServiceServer struct{}

func (UnimplementedPricingServiceServer) GetOptionPrice(context.Context, *GetOptionPriceRequest) (*GetOptionPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOptionPrice not implemented")
}
func (UnimplementedPricingServiceServer) GetGreeks(context.Context, *GetGreeksRequest) (*GetGreeksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGreeks not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}
func (UnimplementedPricingServiceServer) testEmbeddedByValue()                        {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	// If the following call panics, it indicates UnimplementedPricingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_GetOptionPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptionPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetOptionPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetOptionPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetOptionPrice(ctx, req.(*GetOptionPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetGreeks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreeksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetGreeks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetGreeks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetGreeks(ctx, req.(*GetGreeksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricing.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOptionPrice",
			Handler:    _PricingService_GetOptionPrice_Handler,
		},
		{
			MethodName: "GetGreeks",
			Handler:    _PricingService_GetGreeks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing/pricing.proto",
}
