// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/matching-engine/matching.proto

package matching_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingEngineService_SubmitOrder_FullMethodName     = "/matching_engine.MatchingEngineService/SubmitOrder" // MatchingEngineService_SubmitOrder_FullMethodName MatchingEngineSERVICESubmit订单FullMethod名称
	MatchingEngineService_GetOrderBook_FullMethodName    = "/matching_engine.MatchingEngineService/GetOrderBook" // MatchingEngineService_GetOrderBook_FullMethodName MatchingEngineSERVICE获取订单BookFullMethod名称
	MatchingEngineService_GetTrades_FullMethodName       = "/matching_engine.MatchingEngineService/GetTrades" // MatchingEngineService_GetTrades_FullMethodName MatchingEngineSERVICE获取TradesFullMethod名称
	MatchingEngineService_SubscribeTrades_FullMethodName = "/matching_engine.MatchingEngineService/SubscribeTrades" // MatchingEngineService_SubscribeTrades_FullMethodName MatchingEngineSERVICESubscribeTradesFullMethod名称
)

// MatchingEngineServiceClient is the client API for MatchingEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 撮合引擎服务
// MatchingEngineServiceClient 表示MatchingEngineSERVICE客户端结构体。
type MatchingEngineServiceClient interface {
	// 提交订单进行撮合
	SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*MatchResult, error)
	// 获取订单簿
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*OrderBookSnapshot, error)
	// 获取成交记录
	GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*TradesResponse, error)
	// 订阅成交更新（流式）
	SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradeUpdate], error)
}

type matchingEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewMatchingEngineServiceClient 创建新的创建一个新的实例MatchingEngineSERVICE客户端.
func NewMatchingEngineServiceClient(cc grpc.ClientConnInterface) MatchingEngineServiceClient {
	return &matchingEngineServiceClient{cc}
}

// SubmitOrder 执行Submit订单逻辑。
func (c *matchingEngineServiceClient) SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*MatchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResult)
	err := c.cc.Invoke(ctx, MatchingEngineService_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetOrderBook 获取订单Book.
func (c *matchingEngineServiceClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*OrderBookSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderBookSnapshot)
	err := c.cc.Invoke(ctx, MatchingEngineService_GetOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTrades 获取Trades.
func (c *matchingEngineServiceClient) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*TradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_GetTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscribeTrades 执行SubscribeTrades逻辑。
func (c *matchingEngineServiceClient) SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradeUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchingEngineService_ServiceDesc.Streams[0], MatchingEngineService_SubscribeTrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTradesRequest, TradeUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchingEngineService_SubscribeTradesClient = grpc.ServerStreamingClient[TradeUpdate]

// MatchingEngineServiceServer is the server API for MatchingEngineService service.
// All implementations must embed UnimplementedMatchingEngineServiceServer
// for forward compatibility.
//
// 撮合引擎服务
// MatchingEngineServiceServer 表示MatchingEngineSERVICE服务端结构体。
type MatchingEngineServiceServer interface {
	// 提交订单进行撮合
	SubmitOrder(context.Context, *SubmitOrderRequest) (*MatchResult, error)
	// 获取订单簿
	GetOrderBook(context.Context, *GetOrderBookRequest) (*OrderBookSnapshot, error)
	// 获取成交记录
	GetTrades(context.Context, *GetTradesRequest) (*TradesResponse, error)
	// 订阅成交更新（流式）
	SubscribeTrades(*SubscribeTradesRequest, grpc.ServerStreamingServer[TradeUpdate]) error
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

// UnimplementedMatchingEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
// UnimplementedMatchingEngineServiceServer 表示未实现的MatchingEngineSERVICE服务端结构体。
type UnimplementedMatchingEngineServiceServer struct{}

// SubmitOrder 执行Submit订单逻辑。
func (UnimplementedMatchingEngineServiceServer) SubmitOrder(context.Context, *SubmitOrderRequest) (*MatchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
// GetOrderBook 获取订单Book.
func (UnimplementedMatchingEngineServiceServer) GetOrderBook(context.Context, *GetOrderBookRequest) (*OrderBookSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderBook not implemented")
}
// GetTrades 获取Trades.
func (UnimplementedMatchingEngineServiceServer) GetTrades(context.Context, *GetTradesRequest) (*TradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrades not implemented")
}
// SubscribeTrades 执行SubscribeTrades逻辑。
func (UnimplementedMatchingEngineServiceServer) SubscribeTrades(*SubscribeTradesRequest, grpc.ServerStreamingServer[TradeUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTrades not implemented")
}
func (UnimplementedMatchingEngineServiceServer) mustEmbedUnimplementedMatchingEngineServiceServer() {}
func (UnimplementedMatchingEngineServiceServer) testEmbeddedByValue()                               {}

// UnsafeMatchingEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServiceServer will
// result in compilation errors.
// UnsafeMatchingEngineServiceServer 表示UnsafeMatchingEngineSERVICE服务端结构体。
type UnsafeMatchingEngineServiceServer interface {
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

// RegisterMatchingEngineServiceServer 执行RegisterMatchingEngineSERVICE服务端逻辑。
func RegisterMatchingEngineServiceServer(s grpc.ServiceRegistrar, srv MatchingEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchingEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingEngineService_ServiceDesc, srv)
}

func _MatchingEngineService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).SubmitOrder(ctx, req.(*SubmitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_GetOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_GetTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).GetTrades(ctx, req.(*GetTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngineService_SubscribeTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchingEngineServiceServer).SubscribeTrades(m, &grpc.GenericServerStream[SubscribeTradesRequest, TradeUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchingEngineService_SubscribeTradesServer = grpc.ServerStreamingServer[TradeUpdate]

// MatchingEngineService_ServiceDesc is the grpc.ServiceDesc for MatchingEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching_engine.MatchingEngineService",
	HandlerType: (*MatchingEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _MatchingEngineService_SubmitOrder_Handler,
		},
		{
			MethodName: "GetOrderBook",
			Handler:    _MatchingEngineService_GetOrderBook_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _MatchingEngineService_GetTrades_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTrades",
			Handler:       _MatchingEngineService_SubscribeTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/matching-engine/matching.proto",
}
