// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: position/position.proto

package position

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 列表请求。
type GetPositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID。
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 交易对筛选。
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 页码。
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// 每页大小。
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_position_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{0}
}

func (x *GetPositionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPositionsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPositionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPositionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 持仓明细。
type PositionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 持仓 ID。
	PositionId string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// 用户 ID。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 交易对。
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 方向。
	Side string `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	// 数量。
	Quantity string `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// 开仓价。
	EntryPrice string `protobuf:"bytes,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	// 当前价。
	CurrentPrice string `protobuf:"bytes,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	// 未实现盈亏。
	UnrealizedPnl string `protobuf:"bytes,8,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	// 已实现盈亏。
	RealizedPnl string `protobuf:"bytes,9,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	// 开仓时间。
	OpenedAt int64 `protobuf:"varint,10,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	// 平仓时间。
	ClosedAt      int64 `protobuf:"varint,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_position_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{1}
}

func (x *PositionResponse) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PositionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PositionResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionResponse) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PositionResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PositionResponse) GetEntryPrice() string {
	if x != nil {
		return x.EntryPrice
	}
	return ""
}

func (x *PositionResponse) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

func (x *PositionResponse) GetUnrealizedPnl() string {
	if x != nil {
		return x.UnrealizedPnl
	}
	return ""
}

func (x *PositionResponse) GetRealizedPnl() string {
	if x != nil {
		return x.RealizedPnl
	}
	return ""
}

func (x *PositionResponse) GetOpenedAt() int64 {
	if x != nil {
		return x.OpenedAt
	}
	return 0
}

func (x *PositionResponse) GetClosedAt() int64 {
	if x != nil {
		return x.ClosedAt
	}
	return 0
}

// 列表响应。
type PositionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 记录列表。
	Positions []*PositionResponse `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	// 总记录数。
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionsResponse) Reset() {
	*x = PositionsResponse{}
	mi := &file_position_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsResponse) ProtoMessage() {}

func (x *PositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsResponse.ProtoReflect.Descriptor instead.
func (*PositionsResponse) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{2}
}

func (x *PositionsResponse) GetPositions() []*PositionResponse {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *PositionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 单查请求。
type GetPositionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 持仓 ID。
	PositionId string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// 用户 ID。
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_position_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{3}
}

func (x *GetPositionRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *GetPositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 汇总请求。
type GetPositionSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID。
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionSummaryRequest) Reset() {
	*x = GetPositionSummaryRequest{}
	mi := &file_position_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionSummaryRequest) ProtoMessage() {}

func (x *GetPositionSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPositionSummaryRequest) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{4}
}

func (x *GetPositionSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 汇总响应。
type PositionSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总持仓笔数。
	TotalPositions int64 `protobuf:"varint,1,opt,name=total_positions,json=totalPositions,proto3" json:"total_positions,omitempty"`
	// 总未实现盈亏。
	TotalUnrealizedPnl string `protobuf:"bytes,2,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	// 总已实现盈亏。
	TotalRealizedPnl string `protobuf:"bytes,3,opt,name=total_realized_pnl,json=totalRealizedPnl,proto3" json:"total_realized_pnl,omitempty"`
	// 持仓快照列表。
	Positions     []*PositionResponse `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSummaryResponse) Reset() {
	*x = PositionSummaryResponse{}
	mi := &file_position_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSummaryResponse) ProtoMessage() {}

func (x *PositionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSummaryResponse.ProtoReflect.Descriptor instead.
func (*PositionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{5}
}

func (x *PositionSummaryResponse) GetTotalPositions() int64 {
	if x != nil {
		return x.TotalPositions
	}
	return 0
}

func (x *PositionSummaryResponse) GetTotalUnrealizedPnl() string {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return ""
}

func (x *PositionSummaryResponse) GetTotalRealizedPnl() string {
	if x != nil {
		return x.TotalRealizedPnl
	}
	return ""
}

func (x *PositionSummaryResponse) GetPositions() []*PositionResponse {
	if x != nil {
		return x.Positions
	}
	return nil
}

// 平仓请求。
type ClosePositionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 持仓 ID。
	PositionId string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// 用户 ID。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 平仓价格。
	ClosePrice    string `protobuf:"bytes,3,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePositionRequest) Reset() {
	*x = ClosePositionRequest{}
	mi := &file_position_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePositionRequest) ProtoMessage() {}

func (x *ClosePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePositionRequest.ProtoReflect.Descriptor instead.
func (*ClosePositionRequest) Descriptor() ([]byte, []int) {
	return file_position_position_proto_rawDescGZIP(), []int{6}
}

func (x *ClosePositionRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *ClosePositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClosePositionRequest) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

var File_position_position_proto protoreflect.FileDescriptor

const file_position_position_proto_rawDesc = "" +
	"\n" +
	"\x17position/position.proto\x12\bposition\"w\n" +
	"\x13GetPositionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xde\x02\n" +
	"\x10PositionResponse\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\tR\n" +
	"entryPrice\x12#\n" +
	"\rcurrent_price\x18\a \x01(\tR\fcurrentPrice\x12%\n" +
	"\x0eunrealized_pnl\x18\b \x01(\tR\runrealizedPnl\x12!\n" +
	"\frealized_pnl\x18\t \x01(\tR\vrealizedPnl\x12\x1b\n" +
	"\topened_at\x18\n" +
	" \x01(\x03R\bopenedAt\x12\x1b\n" +
	"\tclosed_at\x18\v \x01(\x03R\bclosedAt\"c\n" +
	"\x11PositionsResponse\x128\n" +
	"\tpositions\x18\x01 \x03(\v2\x1a.position.PositionResponseR\tpositions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"N\n" +
	"\x12GetPositionRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x19GetPositionSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdc\x01\n" +
	"\x17PositionSummaryResponse\x12'\n" +
	"\x0ftotal_positions\x18\x01 \x01(\x03R\x0etotalPositions\x120\n" +
	"\x14total_unrealized_pnl\x18\x02 \x01(\tR\x12totalUnrealizedPnl\x12,\n" +
	"\x12total_realized_pnl\x18\x03 \x01(\tR\x10totalRealizedPnl\x128\n" +
	"\tpositions\x18\x04 \x03(\v2\x1a.position.PositionResponseR\tpositions\"q\n" +
	"\x14ClosePositionRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vclose_price\x18\x03 \x01(\tR\n" +
	"closePrice2\xd1\x02\n" +
	"\x0fPositionService\x12J\n" +
	"\fGetPositions\x12\x1d.position.GetPositionsRequest\x1a\x1b.position.PositionsResponse\x12G\n" +
	"\vGetPosition\x12\x1c.position.GetPositionRequest\x1a\x1a.position.PositionResponse\x12\\\n" +
	"\x12GetPositionSummary\x12#.position.GetPositionSummaryRequest\x1a!.position.PositionSummaryResponse\x12K\n" +
	"\rClosePosition\x12\x1e.position.ClosePositionRequest\x1a\x1a.position.PositionResponseB=Z;github.com/fynnwu/FinancialTrading/go-api/position;positionb\x06proto3"

var (
	file_position_position_proto_rawDescOnce sync.Once
	file_position_position_proto_rawDescData []byte
)

func file_position_position_proto_rawDescGZIP() []byte {
	file_position_position_proto_rawDescOnce.Do(func() {
		file_position_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_position_proto_rawDesc), len(file_position_position_proto_rawDesc)))
	})
	return file_position_position_proto_rawDescData
}

var file_position_position_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_position_position_proto_goTypes = []any{
	(*GetPositionsRequest)(nil),       // 0: position.GetPositionsRequest
	(*PositionResponse)(nil),          // 1: position.PositionResponse
	(*PositionsResponse)(nil),         // 2: position.PositionsResponse
	(*GetPositionRequest)(nil),        // 3: position.GetPositionRequest
	(*GetPositionSummaryRequest)(nil), // 4: position.GetPositionSummaryRequest
	(*PositionSummaryResponse)(nil),   // 5: position.PositionSummaryResponse
	(*ClosePositionRequest)(nil),      // 6: position.ClosePositionRequest
}
var file_position_position_proto_depIdxs = []int32{
	1, // 0: position.PositionsResponse.positions:type_name -> position.PositionResponse
	1, // 1: position.PositionSummaryResponse.positions:type_name -> position.PositionResponse
	0, // 2: position.PositionService.GetPositions:input_type -> position.GetPositionsRequest
	3, // 3: position.PositionService.GetPosition:input_type -> position.GetPositionRequest
	4, // 4: position.PositionService.GetPositionSummary:input_type -> position.GetPositionSummaryRequest
	6, // 5: position.PositionService.ClosePosition:input_type -> position.ClosePositionRequest
	2, // 6: position.PositionService.GetPositions:output_type -> position.PositionsResponse
	1, // 7: position.PositionService.GetPosition:output_type -> position.PositionResponse
	5, // 8: position.PositionService.GetPositionSummary:output_type -> position.PositionSummaryResponse
	1, // 9: position.PositionService.ClosePosition:output_type -> position.PositionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_position_position_proto_init() }
func file_position_position_proto_init() {
	if File_position_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_position_proto_rawDesc), len(file_position_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_position_proto_goTypes,
		DependencyIndexes: file_position_position_proto_depIdxs,
		MessageInfos:      file_position_position_proto_msgTypes,
	}.Build()
	File_position_position_proto = out.File
	file_position_position_proto_goTypes = nil
	file_position_position_proto_depIdxs = nil
}
